### ISSUE TITLE
Mult Operation failing if mul operation  is after Unsqueeze operation citing dimension mismatch. The Input from Unsqueeze operation is not transformed when passed as input to Mult

### ISSUE THREAD

**Issue by bediajay** [PINTO0309/onnx2tf#1]
### Issue Type

Others

### Download URL for ONNX

https://act-my.sharepoint.com/personal/WopiFrame.aspx?sourcedoc=%7B35bd9e06-60e0-471a-b50b-7743073d62b8%7D&action=default

### Description

Log added below: One of the inputs. to Mul operation is transformed and the one from Unsqueeze is not transformed

INFO: tf_op_type: Unsqueeze input_name.1: tf.math.divide_1/truediv:0 shape: (1, 72) dtype: <dtype: 'float32'>
INFO: tf_op_type: Unsqueeze output_name.1: 466 shape: (1, 72, 1) dtype: <dtype: 'float32'>
starting to make node
<module 'onnx2tf.ops.Unsqueeze' from '~/onnx2tf/onnx2tf/ops/Unsqueeze.py'>

INFO: onnx_op_type: Unsqueeze onnx_op_name: Unsqueeze_49
INFO: input_name.1: 466 shape: [1, 72, 1] dtype: float32
INFO: output_name.1: 467 shape: [1, 72, 1, 1] dtype: float32
[3]
[1, 72, 1, 1]
[1, 72, 1, 1]
tf.reshape_1/Reshape:0
(1, 72, 1, 1)
True
INFO: tf_op_type: Unsqueeze input_name.1: tf.reshape/Reshape:0 shape: (1, 72, 1) dtype: <dtype: 'float32'>
INFO: tf_op_type: Unsqueeze output_name.1: 467 shape: (1, 72, 1, 1) dtype: <dtype: 'float32'>
starting to make node
<module 'onnx2tf.ops.Mul' from '~/onnx2tf/onnx2tf/ops/Mul.py'>

INFO: onnx_op_type: Mul onnx_op_name: Mul_50
INFO: input_name.1: 453 shape: [1, 72, 60, 60] dtype: float32
INFO: input_name.2: 467 shape: [1, 72, 1, 1] dtype: float32
INFO: output_name.1: 468 shape: [1, 72, 60, 60] dtype: float32
[1, 72, 60, 60]

Traceback (most recent call last):
  File “~/onnx2tf/onnx2tf/utils/common_functions.py", line 49, in print_wrapper_func
    result = func(*args, **kwargs)
  File "~/onnx2tf/onnx2tf/utils/common_functions.py", line 105, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File “~/onnx2tf/onnx2tf/ops/Mul.py", line 61, in make_node
    tf.math.multiply(
  File "~/model-conversion/git/env/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "~/model-conversion/git/env/lib/python3.8/site-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "~/model-conversion/git/env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.math.multiply_3" (type TFOpLambda).

Dimensions must be equal, but are 60 and 72 for '{{node tf.math.multiply_3/Mul}} = Mul[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes: [1,60,60,72], [1,72,1,1].

Call arguments received by layer "tf.math.multiply_3" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 60, 60, 72), dtype=float32)
  • y=tf.Tensor(shape=(1, 72, 1, 1), dtype=float32)
  • name='Mul_50'

**Comment by bediajay** [comment]
I tweaked Mul operation to transform the input tensor from NCHW to NHWC if before_op_output_shape_trans_1 != before_op_output_shape_trans_2 .. And it passed that stage...Do we need to do that ?

**Comment by PINTO0309** [comment]
![image](https://user-images.githubusercontent.com/33194443/195274302-bd14539c-55ad-4b90-9167-720b6d9eaa79.png)

**Comment by PINTO0309** [comment]
Try a model with continuous `Reshape` and `Transpose` with dimensional compression and dimensional expansion and you will see. The transformations will quickly break down. 

The source code modifications you have implemented make sense. 

The download link for the model is broken and I can't verify anything, and since I haven't heard back from you, I'm closing it.
