### ISSUE TITLE
protobuf version issue when trying to install packages in colab

### ISSUE THREAD

**Issue by lhphanto** [PINTO0309/onnx2tf#104]
### Issue Type

Others

### onnx2tf version number

N/A

### onnx version number

N/A

### tensorflow version number

2.10.0

### Download URL for ONNX

N/A

### Parameter Replacement JSON

```json
N/A
```

### Description

I tried to install onnx2tf in colab as instructed
```
!sudo add-apt-repository -y ppa:deadsnakes/ppa
...
!python3.9 -m pip install tensorflow==2.10.0 \
...
  && python3.9 -m pip install -U onnx2tf \
  && python3.9 -m pip install -U protobuf==3.20.3
```

But I got the following error
```
tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
```

Is that expected?

Thanks!

**Comment by PINTO0309** [comment]
>Is that expected?

Yes. You can safely ignore that error; it's a TensorFlow issue, but it doesn't mean much.
