### ISSUE TITLE
[YoloX] output differs between onnx and tflite

### ISSUE THREAD

**Issue by Hyunseok-Kim0** [PINTO0309/onnx2tf#107]
### Issue Type

Others

### onnx2tf version number

1.4.2

### onnx version number

1.12.0

### tensorflow version number

2.10

### Download URL for ONNX

https://drive.google.com/file/d/1QQLf83JwLI_EoQFU5xOGKUvtFPsFSWCN/view

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Personal development
2. What: The outputs are different between onnx and converted tflite. the image below is tflite and onnx outputs consecutively.
<img src="https://user-images.githubusercontent.com/34959032/211462867-f9cf0e62-f142-4662-abbf-7f228ba42654.png" height="300">

3. How: It looks line number 849-855 caused this error in `common_functions.py`. In this case, intermediate `Sub` layer returned wrong output because it didn't re-swapped the parameters. But I didn't fully understand why these lines are needed. What is the bug you mentioned in PR #99?

https://github.com/PINTO0309/onnx2tf/blob/f5eb8720ff0d5f1727601189982a7c18d3b572ae/onnx2tf/utils/common_functions.py#L849-L855

**Comment by PINTO0309** [comment]
Ummm... I see. I've done some harm.  :cry: 

Your original implementation was mostly fine. Recently, however, I have found a pattern of lack of consideration in my many attempts at model transformation.

https://github.com/PINTO0309/onnx2tf/releases/download/1.1.28/damoyolo_tinynasL20_T_192x192_post.onnx

My memory is a little fuzzy on this one, so it may not be accurate.

e.g.
```
X: [1,1,500,1]
Y: [1,500,1,1]
```
```
X: [1,500,1]
Y: [500]
```
```
X: [1,500,1]
Y: [1,1,500]
```
etc...

In my attempt to follow all the patterns I seem to have built the bug backwards.

**Comment by PINTO0309** [comment]
The rest, like the model called SINet, is the first to address the problem that explicit_broadcast was aborting when the two tensors are filled to the maximum number of dimensions from the beginning.

https://github.com/PINTO0309/onnx2tf/pull/64

**Comment by PINTO0309** [comment]
The first bug seems to be in `MaxPool`.

![image](https://user-images.githubusercontent.com/33194443/211559977-f2ee7693-c83e-4c61-a402-f7f617c07770.png)

1. `Mul`
    ```
    onnx2tf -i yolox_x.onnx -onimc onnx::MaxPool_1250
    ``` 
    ![image](https://user-images.githubusercontent.com/33194443/211560351-a51d9a93-9519-47ba-a29b-50a769a8c93a.png)

2. `Concat`
    ```
    onnx2tf -i yolox_x.onnx -onimc input.555
    ``` 
    ![image](https://user-images.githubusercontent.com/33194443/211560594-65c696c6-a9e7-4823-86e7-c2dd13e2fff1.png)

**Comment by PINTO0309** [comment]
The second bug seems to be occurring in `Conv2D`, but I don't know what is wrong at the moment. `Conv_310`
![image](https://user-images.githubusercontent.com/33194443/211574766-f2d07d98-b4d6-4506-ad4f-12f3331804d3.png)

**Comment by PINTO0309** [comment]
They seem to be almost in agreement.
![image](https://user-images.githubusercontent.com/33194443/211692482-9f35dc51-025d-47b3-a4d2-02f02538649c.png)

```
onnx2tf -i yolox_x.onnx -coto -onimc onnx::Unsqueeze_1745 -cotoa 1e-1
```
```
saved_model output started ==========================================================
saved_model output complete!
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
Estimated count of arithmetic ops: 726.541 G  ops, equivalently 363.270 G  MACs
Float32 tflite output complete!
Estimated count of arithmetic ops: 726.541 G  ops, equivalently 363.270 G  MACs
Float16 tflite output complete!

ONNX and TF output value validation started =========================================
INFO: validation_conditions: np.allclose(onnx_outputs, tf_outputs, rtol=0.0, atol=0.1, equal_nan=True)
INFO: onnx_output_name: onnx::Unsqueeze_1745 shape: (1, 23625) dtype: float32 validate_result:  Matches 
```
![image](https://user-images.githubusercontent.com/33194443/211690944-1ce15869-cfc5-4c76-be7a-3dd41db95ab2.png)

**Comment by Hyunseok-Kim0** [comment]
Great works. Now it looks working properly.

**Comment by PINTO0309** [comment]
Added the ability for the tool to automatically identify operations with large model accuracy errors.

https://user-images.githubusercontent.com/33194443/211809221-d651bdcd-149f-42c1-aeec-2e43dc5aaa1e.mp4

**Comment by PINTO0309** [comment]
I close this issue because I have heard good news from you that the accuracy of the model is now correct after the conversion. 

Thank you for your cooperation. :+1:

**Comment by PINTO0309** [comment]
I modified it to throw in dummy data as shown in the image so that it matches up to the final output of the model. However, absolute errors of 1e-4 or less seem to leave a small margin of error.
![image](https://user-images.githubusercontent.com/33194443/212195579-90a7ebc1-fa4b-4b42-baf5-9b20aeb01eac.png)
