### ISSUE TITLE
Bug in `onnx_tf_tensor_validation`

### ISSUE THREAD

**Issue by Hyunseok-Kim0** [PINTO0309/onnx2tf#139]
### Issue Type

Others

### onnx2tf version number

1.5.23

### onnx version number

1.12.0

### tensorflow version number

2.10

### Download URL for ONNX

https://github.com/PINTO0309/onnx2tf/releases/download/1.1.28/pidnet_S_cityscapes_192x320.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Personal development
2. What: `onnx_tf_tensor_validation` use tensor shape to find out matching pairs between onnx and tflite outputs. Due to this logic, some outputs are failed to matched and generates wrong absolute error.
<img src="https://user-images.githubusercontent.com/34959032/213646230-ffac69a0-6354-4878-a089-9e864aa9f547.png" height="400">

The output of global average pooling has shape of (1 x 512 x 1 x 1), and another average pooling output also have same shape and same value. When `onnx_tf_tensor_validation` is running, the output of global average pooling is failed to be matched with correct onnx output, generates `Unmatched` result as below.

![Screenshot from 2023-01-20 17-06-40](https://user-images.githubusercontent.com/34959032/213646710-719f1225-57fb-427b-b9f7-be1bbdf7be1d.png)

Similar bug can be happen in other onnx files if some outputs have same shape and same value.

**Comment by PINTO0309** [comment]
I see. 

Originally, before the process of validation was made ultra-fast, the size of the error was determined by comparing the output of each OP with the results of dummy inference from the top to the bottom, but after the speed was increased by changing to the batch inference method, it seems that consideration for tensors with the same shape was insufficient.

**Comment by Hyunseok-Kim0** [comment]
It would be easy if matching the order of onnx and tensorflow output is possible. That can make output comparing much faster since current implementation use for loop and permutation to match the shape between all tensors.

**Comment by PINTO0309** [comment]
Hmmm. It might be a surprising struggle. :thinking:

**Comment by PINTO0309** [comment]
The validation algorithm was reviewed to eliminate unnecessary loops. Also, as you suggested, we have reviewed the comparison of the ONNX and TensorFlow output OPs with their prior correspondence. 

If an OP is deleted in the process of model optimization, or if the output shape is unmatched, it is changed to show `Skipped (Deleted or Shape Unmatched)`. Thus, `GlobalAveragePool (/spp/scale4/scale4.0/GlobalAveragePool_output_0)` now succeeds in validation, but a shape mismatch in `AveragePool (/spp/scale2/scale2.0/AveragePool_output_0 or /spp/scale3/scale3.0/AveragePool_output_0)` is detected.
https://github.com/PINTO0309/onnx2tf/releases/tag/1.5.27
![image](https://user-images.githubusercontent.com/33194443/213902264-e7f08259-beab-4d33-b919-bc96c04f7ffc.png)

**Comment by Hyunseok-Kim0** [comment]
> If an OP is deleted in the process of model optimization, or if the output shape is unmatched, it is changed to show Skipped (Deleted or Shape Unmatched). Thus, GlobalAveragePool (/spp/scale4/scale4.0/GlobalAveragePool_output_0) now succeeds in validation, but a shape mismatch in AveragePool (/spp/scale2/scale2.0/AveragePool_output_0 or /spp/scale3/scale3.0/AveragePool_output_0) is detected.

I think that error still is not fixed. I will fix it within upcoming week in PR #138

**Comment by PINTO0309** [comment]
Thank you so much!

**Comment by PINTO0309** [comment]
Continued investigation. https://github.com/PINTO0309/onnx2tf/pull/138#issuecomment-1402884230
![image](https://user-images.githubusercontent.com/33194443/214461349-c7c7586f-9529-41a6-a52e-54f6d20cfc15.png)

**Comment by Hyunseok-Kim0** [comment]
I think something went wrong when `average_multiplier` is calculated and used in `AveragePool.py` when certain output dimension became 1.

**Comment by PINTO0309** [comment]
This issue seems to be quite difficult. Thank you so much for your intensive help.
It is good if we can improve little by little. :+1:

**Comment by Hyunseok-Kim0** [comment]
It looks this problem resolved in last PR. Closing issue.
