### ISSUE TITLE
For min_value and max_value in Clip.py

### ISSUE THREAD

**Issue by swatanabe1** [PINTO0309/onnx2tf#14]
### Issue Type

Others

### onnx2tf version number

1.1.17

### Download URL for ONNX

[japan_PP-OCRv3_rec_infer.zip](https://github.com/PINTO0309/onnx2tf/files/9969436/japan_PP-OCRv3_rec_infer.zip)

### Parameter Replacement JSON

```json
None
```

### Description

`onnx2tf -i japan_PP-OCRv3_rec_infer.onnx`

```
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/systemkjapan/.local/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 261, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/systemkjapan/.local/lib/python3.8/site-packages/onnx2tf/utils/common_functions.py", line 323, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/systemkjapan/.local/lib/python3.8/site-packages/onnx2tf/ops/Clip.py", line 109, in make_node
    if (min_value is not None and min_value.shape is not None) \
AttributeError: 'float' object has no attribute 'shape'
```

I don't think the code here will work if 'min_value' is 'float'?
Or is it wrong to be 'float'?

**Comment by PINTO0309** [comment]
Thanks for pointing that out, I didn't take into account the logic of the opset<11 pattern.
I have just fixed and released it. If you are still interested, give it a try.

Fixes commit: https://github.com/PINTO0309/onnx2tf/commit/ff349250bd53e01b36cc1db5318c38749884df00
Release: https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.18

- replace.json
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "Transpose_7",
        "param_target": "attributes",
        "param_name": "perm",
        "values": [0,1,2,3]
      }
    ]
  }
  ```
- run
  ```
  onnx2tf -i japan_PP-OCRv3_rec_infer.onnx -prf replace.json
  ```
- Converted tflite
[model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/9969775/model_float32.tflite.zip)

**Comment by swatanabe1** [comment]
Thanks for the quick response. It can now be converted.
I will refer to your remarks as well.

**Comment by PINTO0309** [comment]
After v1.1.46 https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.46
replace.json is no longer needed.
```
pip install onnx2tf -U
onnx2tf -i japan_PP-OCRv3_rec_infer.onnx
```

**Comment by PINTO0309** [comment]
Fixes: `BatchMatMul`, `DepthwiseConv2D`
https://github.com/PINTO0309/onnx2tf/releases/tag/1.5.28
https://github.com/PINTO0309/onnx2tf/blob/1.5.28/json_samples/replace_japan_PP-OCRv3_rec_infer.json
