### ISSUE TITLE
[ALIKE] Inference error for `MaxPool` with padding is very large

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#155]
### Issue Type

Others

### onnx2tf version number

1.5.33

### onnx version number

1.13.1

### tensorflow version number

2.10.0

### Download URL for ONNX

https://github.com/PINTO0309/onnx2tf/releases/download/1.1.28/alike_t_opset11_192x320.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Personal
2. Inference error for `MaxPool` with padding is very large. However, I believe a separate investigation is needed to determine if this is a problem with the logic used to verify accuracy or with MaxPool's padding process.
  https://github.com/PINTO0309/onnx2tf/releases/download/1.1.28/alike_t_opset11_192x320.onnx
  ![image](https://user-images.githubusercontent.com/33194443/215308324-14b17470-9d47-4d52-a711-a2b6946150eb.png)
  ![image](https://user-images.githubusercontent.com/33194443/215308272-e20a6d65-00ee-461e-8099-b15b21cbf938.png)

**Comment by Hyunseok-Kim0** [comment]
<img src="https://user-images.githubusercontent.com/34959032/215372875-daeb034c-acd9-42d8-a8af-baf8c18d41ee.png" height="350">
I guess this reshape is cause of the problem. After that reshape, channel-last changed to channel-first, which is not appropriate for tensorflow.

**Comment by PINTO0309** [comment]
Great insight!

**Comment by PINTO0309** [comment]
O.K.
https://github.com/PINTO0309/onnx2tf/blob/main/json_samples/replace_alike.json
![image](https://user-images.githubusercontent.com/33194443/215472242-b94537f1-9ad6-4bd1-95fa-47d61f24eadc.png)
