### ISSUE TITLE
[ConvNext] Add layer shape wrong

### ISSUE THREAD

**Issue by jj198378** [PINTO0309/onnx2tf#17]
### Issue Type

Others

### onnx2tf version number

1.1.24

### Download URL for ONNX

https://drive.google.com/file/d/15TV0y-Go0VYdyV4FKNhciVDWa3frECfm/view?usp=sharing

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/encoder/stages.0/layers/layers.0/Transpose_1",
      "param_target": "outputs",
      "param_name": "/encoder/stages.0/layers/layers.0/Transpose_1_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    }
  ]
}
```

### Description

Hi - thanks for the super useful library. 

I'm having trouble diagnosing the problem with an add op - I've narrowed it down to the op, but can't seem to get the right adjustment in the parameter_replacement.json file to fix it, and am not sure exactly how to spot the issue in the attached screenshots. 

![image](https://user-images.githubusercontent.com/118408638/202329469-a8d44813-813c-4c52-9804-bf58b401a746.png)

![image](https://user-images.githubusercontent.com/118408638/202329597-7b3d4d7e-4a7b-42bb-8b4e-46a50bce6094.png)

Many thanks!

**Comment by jj198378** [comment]
https://drive.google.com/file/d/15TV0y-Go0VYdyV4FKNhciVDWa3frECfm/view?usp=sharing

**Comment by PINTO0309** [comment]
The tutorial for changing the transposition order of Transpose requires changing the attribute `perm` as described in the README.
https://github.com/PINTO0309/onnx2tf#parameter-replacement

![image](https://user-images.githubusercontent.com/33194443/202332492-8dd6c6e6-0376-415c-b085-de0614e3b067.png)
![image](https://user-images.githubusercontent.com/33194443/202332537-51067362-c41a-4e92-8d9a-cee34952145e.png)


- replace.json
```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/encoder/stages.0/layers/layers.0/Transpose_1",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    }
  ]
}
```
```
onnx2tf -i convnext.onnx -prf replace.json
```
The convnext.onnx you provided seems to contain dozens of unnecessary `Transpose` similar to this one, so you need to append the same to your JSON to disable all transpositions.

If you succeed in the conversion through your efforts, it would be very helpful to share the completed JSON file in this issue, as it will serve as knowledge for engineers around the world. Please share the completed JSON if possible.

**Comment by PINTO0309** [comment]
In the current latest version v1.1.38, the conversion can be done successfully without creating a JSON file.
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.38
