### ISSUE TITLE
Conversion fails with ONNX with `:` in node names

### ISSUE THREAD

**Issue by Hyunseok-Kim0** [PINTO0309/onnx2tf#186]
### Issue Type

Others

### onnx2tf version number

1.6.5

### onnx version number

1.12.0

### tensorflow version number

2.10

### Download URL for ONNX

https://github.com/PINTO0309/onnx2tf/releases/download/1.1.28/efficientdet_lite2_detection_1.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Personal development
2. What: ![Screenshot from 2023-02-13 10-14-14](https://user-images.githubusercontent.com/34959032/218350543-08f676c0-f803-443c-9579-4ab1df6df056.png) Some ONNX node name contains `:`, which makes problem in code block below. I didn't make PR since this problem can be resolved easily using simple replace like `output.node.layer._name = name.replace(':', '_')` in line 778. Please review about this error and include the fix in your next commit if possible.
https://github.com/PINTO0309/onnx2tf/blob/7b13ff19990c32d5af75fccaa251291ed7a8b43e/onnx2tf/onnx2tf.py#L776-L778

**Comment by PINTO0309** [comment]
Thanks. :)

I forgot to issue a pull request, but I have released it with the fixes.
https://github.com/PINTO0309/onnx2tf/releases/tag/1.6.6
