### ISSUE TITLE
Clip operation assuming min/max as input nodes but these are set as attributes in onnx graph

### ISSUE THREAD

**Issue by bediajay** [PINTO0309/onnx2tf#2]
### Issue Type

Others

### Download URL for ONNX

Generic issue

### Description

Clip operation failing as min max are assumed to be inputs .. But. in onnx graph. they may be set as attributes.

**Comment by PINTO0309** [comment]
https://github.com/onnx/onnx/blob/main/docs/Changelog.md#clip-11
![image](https://user-images.githubusercontent.com/33194443/195274709-81c280ee-11fb-4583-8012-9ade9e327a54.png)

https://github.com/PINTO0309/onnx2tf#key-concept
![image](https://user-images.githubusercontent.com/33194443/195274804-e418e1a4-629c-41b0-994a-00020602fa56.png)

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/compare/0.0.23...0.0.24
https://github.com/PINTO0309/onnx2tf/releases/tag/0.0.24

**Comment by bediajay** [comment]
thanks a lot. it worked.. but with small tweak.. we are accessing index of 1 and 2 in the inputs which will not be available for attributes case.

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/compare/1.0.48...1.0.49
https://github.com/PINTO0309/onnx2tf/releases/tag/1.0.49
