### ISSUE TITLE
The h5 or keras model takes up a lot of space and need a long time to load

### ISSUE THREAD

**Issue by duanshengliu** [PINTO0309/onnx2tf#200]
### Issue Type

Others

### onnx2tf version number

1.6.7

### onnx version number

1.13.0

### tensorflow version number

2.10.0

### Download URL for ONNX

https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-10.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

Purpose: Sorry to bother, I have been using your tool for a while and it works great. But I have 2 problems,
**question 1**   is that  **if I export the h5 or keras model, the model takes up a lot of space and need a long time to load**, such as [mobilenetv2.onnx](https://github.com/onnx/models/raw/main/vision/classification/mobilenet/model/mobilenetv2-10.onnx)：

![image](https://user-images.githubusercontent.com/44742794/220684415-d120e0fb-78d0-48bd-bf54-672c85f208aa.png)

**Sometimes  the keras model cannot be visualized by netron. Almost all models have this problem.**  I think the problem is caused by operators such as  **tf.nn.convolution, and the weights information of the model are stored in the form of  string(I guess)** like this：
![image](https://user-images.githubusercontent.com/44742794/220685674-87708a11-a6b5-4404-b624-2c592b499d43.png)
so the model cannot be stored like a native keras model , **I wonder why not use the Conv2D in tf.keras.layers?**

**question 2**  is that I don't know **how to use  ‘tf.lite.TFLiteConverter.from_saved_model’ to load the save_model** exported by onnx2tf, which always prompts the following error message:

![IDUW4P_% Y~_UE%BR3OSM7V](https://user-images.githubusercontent.com/44742794/220683816-22500739-210e-4e85-a0b3-f2a436de90c9.png)

Can these two problems be solved? Thank you very much!!!

**Comment by PINTO0309** [comment]
1. I see. So there is such a problem. Would using `tf.keras.Conv2D` improve this? Incidentally, all operations other than `Convolution` also use Keras operations as little as possible.

2. Please read the README carefully first. For speed, model export by concrete function is used by default, so only the minimum information necessary to generate a tflite is output.
```
  -osd, --output_signaturedefs
    Signature is added to the output for serving or for conversion
    to other model formats. However, this can significantly reduce the speed
    of model conversion and significant increase the size of the model.
```

**Comment by duanshengliu** [comment]
I see. Your answer solved my problems, thanks.
