### ISSUE TITLE
[EleGANt] [IF_]ERROR:onnx_op_name:If_761

### ISSUE THREAD

**Issue by TomatoBoy90** [PINTO0309/onnx2tf#223]
### Issue Type

Others

### onnx2tf version number

1.7.13

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc0

### Download URL for ONNX

https://drive.google.com/file/d/164X9DBe-1tZlUuJ6JZs5kw0aCyK-08IF/view?usp=sharing

### Parameter Replacement JSON

```json
{}
```

### Description

1.I want to convert onnx to tflite in my model, but for some reason there are a lot of useless nodes If_XXX, causing me to fail the conversion.
![image](https://user-images.githubusercontent.com/40761785/222683445-97cf90af-8861-450a-a9c6-81c7f4036906.png)

my onnx file  visualization is as follows:
![image](https://user-images.githubusercontent.com/40761785/222683965-5d76e208-271f-47c6-92e8-418576d75813.png)

Because of the complex structure of the model, the use of -dsf can not completely remove the flexTranspose, so they made their own split.
The torch code that leads to IF_XXX is as follows:
```
# mask = mask.permute(0, 1, 3, 4, 5, 2)
  mask = torch.squeeze(mask, 1)
  mask = mask.permute(0, 3, 2, 4, 1)
  mask = torch.unsqueeze(mask, 1)
```

**Comment by PINTO0309** [comment]
There is no `IF` OP in the ONNX file you shared with me.
![image](https://user-images.githubusercontent.com/33194443/222689884-22d54f84-243c-4009-a5bb-76d8dfa876d8.png)

**Comment by PINTO0309** [comment]
[model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/10880778/model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze.onnx.zip)

**Comment by PINTO0309** [comment]
Don't complicate matters. You should try to optimize the model first in order to handle it as simply as possible.

**Comment by TomatoBoy90** [comment]
> [model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/10880778/model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze.onnx.zip)

Thank you very much, can you tell us how you modified this onnx model?

**Comment by TomatoBoy90** [comment]
> I just executed the above command.
Okay, thank you and have a great day!
