### ISSUE TITLE
[EleGANt][FullyConnected] GPU Delegate aborts as `MatMul` is converted to `FullyConnected` layer. Also, generation of `FlexBatchMatMul` by `MatMul` in 6 dimensions.

### ISSUE THREAD

**Issue by TomatoBoy90** [PINTO0309/onnx2tf#233]
### Issue Type

Others

### onnx2tf version number

1.7.13

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc0

### Download URL for ONNX

https://drive.google.com/file/d/164X9DBe-1tZlUuJ6JZs5kw0aCyK-08IF/view?usp=sharing

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/attention_extract_2/value/Reshape_3",
      "param_target": "outputs",
      "param_name": "/attention_extract_2/value/Reshape_3_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/attention_extract_1/window_attention_3/Reshape",
      "param_target": "outputs",
      "param_name": "/attention_extract_1/window_attention_3/Reshape_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/attention_extract_1/window_attention_1/Reshape",
      "param_target": "outputs",
      "param_name": "/attention_extract_1/window_attention_1/Reshape_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/attention_extract_1/window_attention/Reshape_5",
      "param_target": "outputs",
      "param_name": "/attention_extract_1/window_attention/Reshape_5_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "/attention_extract_1/window_attention_2/Reshape",
      "param_target": "outputs",
      "param_name": "/attention_extract_1/window_attention_2/Reshape_output_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Reshape_2079",
      "param_target": "outputs",
      "param_name": "onnx::Add_2633",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Add_2084",
      "param_target": "outputs",
      "param_name": "onnx::Mul_2638",
      "post_process_transpose_perm": [0,2,3,1]
    }
  ]
}
```

### Description

My onnx file is without FullyConnected, but the transferred tflite appears several extra FullyConnected. I compared the node of onnx and tflite, and found that tflite is extra FullyConnected node.
And the gpu of tflite does not support FullyConnected(https://github.com/tensorflow/tensorflow/issues/34525#issuecomment-564755977), so I want to get rid of this FullyConnected.
![image](https://user-images.githubusercontent.com/40761785/223645558-6a7f0676-287b-48a4-8158-422c18b6807b.png)
![image](https://user-images.githubusercontent.com/40761785/223646794-e214f2e9-53e9-41a0-b6b6-5d08f537bf34.png)

**Comment by PINTO0309** [comment]
https://github.com/Bahar-BM/dense_3D_inputs

**Comment by PINTO0309** [comment]
https://github.com/tensorflow/tensorflow/issues/57180

**Comment by PINTO0309** [comment]
https://github.com/tensorflow/tensorflow/issues/58607

**Comment by TomatoBoy90** [comment]
> [tensorflow/tensorflow#58607](https://github.com/tensorflow/tensorflow/issues/58607)
My onnx model does not have a fully connected layer, it is a redundant fully connected layer created after using onnx2tf.

**Comment by PINTO0309** [comment]
Your model has a `FullyConnected` layer. This is the specification of the optimizer in TensorFlow Lite; onnx2tf is just faithfully transforming the model.
![image](https://user-images.githubusercontent.com/33194443/223699757-88472dc5-1a71-4a1a-9ec0-810990e09a6d.png)

[model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/10920028/model_70_2023_0303_32_2_1_grid_sample_bilinear_no_pad_10_squeeze_float32.tflite.zip)

**Comment by PINTO0309** [comment]
https://www.tensorflow.org/lite/performance/gpu#supported_ops

![image](https://user-images.githubusercontent.com/33194443/223703608-a0862226-9952-40cd-94e0-ec3cda296686.png)

**Comment by PINTO0309** [comment]
Another location seems to contain a high-dimensional `MatMul`, so even the standard runtime CPU inference will not work.

![image](https://user-images.githubusercontent.com/33194443/223704275-9c48991a-9a75-437e-986a-e020470cecad.png)

![image](https://user-images.githubusercontent.com/33194443/223704363-615a63fc-76b9-4210-84ab-9e6582cf97ac.png)

**Comment by TomatoBoy90** [comment]
> https://www.tensorflow.org/lite/performance/gpu#supported_ops
> 
> ![image](https://user-images.githubusercontent.com/33194443/223703608-a0862226-9952-40cd-94e0-ec3cda296686.png)
I am very sorry I shared the wrong file, the correct connection is as follows.

https://drive.google.com/file/d/1X0y6yCpmn04YWM6VSHqBB_VVgAzWPtQb/view?usp=share_link

**Comment by PINTO0309** [comment]
https://blog.shikoan.com/conv2d-matmul/

**Comment by PINTO0309** [comment]
Unfortunately, it's impossible. TFLite's optimizer seems to extrapolate the batch dimension on its own and corrupt the model into a format that cannot be executed on GPU Delegate. 
- Temporary Customization
  ![image](https://user-images.githubusercontent.com/33194443/223883764-f3ec962f-d67d-4bf4-8aa9-7e726b3cfa6a.png)
- tflite
  ![image](https://user-images.githubusercontent.com/33194443/223884360-c8c4eabc-ceb0-419d-a446-d8c392cff25c.png)

It might work to insert Squeeze just before the FullyConnected layer after converting to TFLite.
https://github.com/PINTO0309/tflite2json2tflite

**Comment by PINTO0309** [comment]
Or try the `-ebu`,`--enaable_batchmatmul_unfold` options.

**Comment by TomatoBoy90** [comment]
> Or try the `-ebu`,`--enaable_batchmatmul_unfold` options.
when use the `-ebu`, open tflite flile with Netron will show:
![image](https://user-images.githubusercontent.com/40761785/223930020-e2b57403-de7d-45b1-8e67-066858a3ea31.png)
![image](https://user-images.githubusercontent.com/40761785/223930263-7ba34653-9ac8-4483-b92e-b6982817de1b.png)

**Comment by TomatoBoy90** [comment]
However, there is almost no difference in the size of the model, but this latter will not open the tflite file.

**Comment by PINTO0309** [comment]
Wait 5 minutes and it will open. 

Since all `BatchMatMul` is broken down into `MatMul`, the total number of operations has only increased considerably. Thus, maybe it could be adapted to your application, but please try the inference once.

**Comment by PINTO0309** [comment]
If you are using the browser version of Netron I would not recommend it. 

It is recommended to use the local execution version.
https://github.com/lutzroeder/netron#install

**Comment by PINTO0309** [comment]
If it does not work, the last verification would be to downgrade to TensorFlow v2.3.0 and try it. If it still does not work, there is no way to counteract it.
