### ISSUE TITLE
[TODO] Implement additional `dilations` attribute to the `AveragePool` operation. `opset=19`

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#239]
### Issue Type

Others

### onnx2tf version number

1.7.22

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc1

### Download URL for ONNX

N/A

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Personal
2. Implement additional `dilations` attribute to the `AveragePool` operation. `opset=19`
    https://github.com/onnx/onnx/blob/main/docs/Changelog.md#averagepool-19
    ```
    dilations : list of ints
      Dilation value along each spatial axis of filter.
      If not present, the dilation defaults to 1 along each spatial axis.
    ```

**Comment by Hyunseok-Kim0** [comment]
The logic for `dilations` in `AveragePool` is already implemented, but I couldn't test it due to failure in inference. I guess inference for opset 19 is not ready yet. Inference using onnx `ReferenceEvaluator` and onnxruntime failed when `dilations` property is included in `AveragePool`.
Do you have any inference code for it?

**Comment by PINTO0309** [comment]
Thanks for checking.

New specifications are added to the README of ONNX's Opset earlier than the latest version of the runtime is released. Therefore, to ensure that we do not miss any tasks to test when the latest version of the runtime is released, we give TODO tags and continuously leave issues, and set the bot not to auto-close them.

At the moment, I think the only way to try it is to build onnxrutnime, etc. by ourselves from the main branch, but that would be very time-consuming, so I have registered an issue and put the testing and implementation on hold.
