### ISSUE TITLE
[BERT-Squad] INT8 quantization: The input data type must be Float32. 

### ISSUE THREAD

**Issue by InputBlackBoxOutput** [PINTO0309/onnx2tf#248]
### Issue Type

Others

### onnx2tf version number

1.7.25

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc1

### Download URL for ONNX

https://github.com/onnx/models/blob/main/text/machine_comprehension/bert-squad/model/bertsquad-12.onnx

### Parameter Replacement JSON

```json
None
```

### Description

Hi,

I am trying to convert and INT8 quantize a BERT ONNX model. I am using the following command on my setup on Google Colab.

```
onnx2tf --output_integer_quantized_tflite -i {MODEL}.onnx -b 1 > {MODEL}.log
```

Ouput:
```
Model convertion started
============================================================

ERROR: For INT8 quantization, the input data type must be Float32. Also, if --quant_calib_input_op_name_np_data_path is not specified, all input OPs must assume 4D tensor image data. INPUT Name: unique_ids_raw_output___9:0 INPUT Shape: ['unk__492'] INPUT dtype: int64
```

I believe the model has int64 as the input datatype, causing the onnx2tf to fail. Is there a workaround for this ?

<img width="746" alt="image" src="https://user-images.githubusercontent.com/53337979/224908021-61776f43-a1d2-424f-8742-7d0296890463.png">

Thanks for creating such a fantastic tool!

**Comment by InputBlackBoxOutput** [comment]
Please guide me on how to work around the Auto Calibration Check. I do not need the model to be accurate. I only need the model for hardware profiling for latency.

https://github.com/PINTO0309/onnx2tf/blob/df183f18dcb02265cb6af7444f8f719643c5311d/onnx2tf/onnx2tf.py#L722-L733

**Comment by PINTO0309** [comment]
If you do not need to perform INT8 quantization with this tool alone, the following method is the easiest.

The `-osd` option will output a `saved_model.pb ` in the `saved_model` folder with the full size required for quantization.
```
onnx2tf -i {MODEL}.onnx -b 1 -osd
```

Next, simply follow the official tutorial to write and run a few lines of quantization source code.
https://www.tensorflow.org/lite/performance/post_training_quantization

```python
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
```

**Comment by InputBlackBoxOutput** [comment]
Hi @PINTO0309, 
I got it working. Heres what I did:

```python
import tensorflow as tf
import numpy as np

# Output of command: saved_model_cli show --dir saved_model/ --all
  # The given SavedModel SignatureDef contains the following input(s):
  #   inputs['input_ids_0'] tensor_info:
  #       dtype: DT_INT64
  #       shape: (1, 256)
  #       name: serving_default_input_ids_0:0
  #   inputs['input_mask_0'] tensor_info:
  #       dtype: DT_INT64
  #       shape: (1, 256)
  #       name: serving_default_input_mask_0:0
  #   inputs['segment_ids_0'] tensor_info:
  #       dtype: DT_INT64
  #       shape: (1, 256)
  #       name: serving_default_segment_ids_0:0
  #   inputs['unique_ids_raw_output___9_0'] tensor_info:
  #       dtype: DT_INT64
  #       shape: (1)
  #       name: serving_default_unique_ids_raw_output___9_0:0

def representative_dataset():
    yield {
      'input_ids_0': np.array([1 for i in range(256)]),
      'input_mask_0': np.array([1 for i in range(256)]),
      'segment_ids_0': np.array([1 for i in range(256)]),
      'unique_ids_raw_output___9_0': np.array([1]),
    }

converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()

with open('saved_model/int8_model.tflite', 'wb') as w:
  w.write(tflite_quant_model)
```



Thanks for the help!

**Comment by MrRace** [comment]
@InputBlackBoxOutput From you representative_dataset
```
def representative_dataset():
    yield {
      'input_ids_0': np.array([1 for i in range(256)]),
      'input_mask_0': np.array([1 for i in range(256)]),
      'segment_ids_0': np.array([1 for i in range(256)]),
      'unique_ids_raw_output___9_0': np.array([1]),
    }
```
Your calibration data is so simple, is that OK?

**Comment by InputBlackBoxOutput** [comment]
Hi @MrRace 
I wanted to convert the model for profiling purpose only hence quantization accuracy was not taken into account during conversation. You will have to modify the code to make the representative dataset work.
