### ISSUE TITLE
Incorrect tensor shape when converting a model with "torch.randn_like"

### ISSUE THREAD

**Issue by stealthinu** [PINTO0309/onnx2tf#253]
### Issue Type

Others

### onnx2tf version number

1.7.28

### onnx version number

1.13.1

### tensorflow version number

2.12.0rc1

### Download URL for ONNX

[randnlike4.zip](https://github.com/PINTO0309/onnx2tf/files/11000355/randnlike4.zip)

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose
Product development

2. What
I encountered an issue when trying to convert an ONNX file using onnx2tf. The error message I received is as follows:

```text
Dimensions must be equal, but are 256 and 73 for '{{node tf.math.multiply_349/Mul}} = Mul[T=DT_FLOAT](tf.math.multiply_349/Mul/x, Placeholder)' with input shapes: [1,256,73], [1,73,256].

Call arguments received by layer "tf.math.multiply_349" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 256, 73), dtype=float32)
  • y=tf.Tensor(shape=(1, 73, 256), dtype=float32)
  • name=None
ERROR: input_onnx_file_path: logs/20230212_15test1/G_200000.onnx
ERROR: onnx_op_name: /enc_q/Mul_2
```

3. How
I extracted the problematic part of the code and created a smaller test script to verify if the issue could be reproduced. Based on the test code and the results, it appears that there is a problem with the conversion of the "torch.randn_like" function.

Here is the example code to reproduce the issue:
```python
import torch

class OnnxTestRandnLike(torch.nn.Module):
    def forward(self, x):
        m = torch.randn_like(x)
        y = m * x
        return y

class OnnxTestRandn(torch.nn.Module):
    def forward(self, x):
        m = torch.randn(x.size())
        y = m * x
        return y

def export_onnx(x, net, file):
    torch.onnx.export(
        net,
        x,
        file,
        opset_version=17,
        verbose=False,
        input_names=["x"],
        output_names=["y"])
    print("Done: " + file)

def main():
    export_onnx(torch.rand(1, 2, 4), OnnxTestRandnLike(), "randnlike4.onnx")
    export_onnx(torch.rand(1, 2, 4), OnnxTestRandn(), "randn4.onnx")

if __name__ == '__main__':
    main()
```

When converting the ONNX model created with torch.randn_like (randnlike4.onnx) to TensorFlow, I get the following error:
```text
Dimensions must be equal, but are 2 and 4 for '{{node tf.math.multiply_2/Mul}} = Mul[T=DT_FLOAT](tf.math.multiply_2/Mul/x, Placeholder)' with input shapes: [1,2,4], [1,4,2].

Call arguments received by layer "tf.math.multiply_2" (type TFOpLambda):
  • x=tf.Tensor(shape=(1, 2, 4), dtype=float32)
  • y=tf.Tensor(shape=(1, 4, 2), dtype=float32)
  • name=None
ERROR: input_onnx_file_path: randnlike4.onnx
ERROR: onnx_op_name: /Mul
```
The output tensor shape becomes (1, 4, 2) instead of the expected (1, 2, 4).

In the case of the model using torch.randn (randn4.onnx), no errors were encountered.

4. Why
I would like to make these modifications because I want to run the model in TFLite.

5. Resources
None

**Comment by PINTO0309** [comment]
The input OP is just automatically transposed from NCW to NWC. Therefore, it is correct behavior for an error to occur. This tool has the ability to disable automatic transposition of input OPs by specifying the `-kat` option as shown below.
```
onnx2tf -i randnlike4.onnx -kat x
```
![image](https://user-images.githubusercontent.com/33194443/225885565-d06d60b0-ec8a-4d6f-a320-e875bc71565e.png)

[randnlike4_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/11000572/randnlike4_float32.tflite.zip)

Please read the README carefully.

**Comment by PINTO0309** [comment]
https://github.com/isletennos/MMVC_Trainer

```
onnx2tf -i D_180000.onnx
```
![image](https://user-images.githubusercontent.com/33194443/226112045-89419ee8-edc7-4f21-9de9-1cda4264fc9d.png)

**Comment by PINTO0309** [comment]
I don't know what name model you are converting, but please note that `RandomNormalLike` and `RandomUniformLike` do not support undefined dimensions.

![image](https://user-images.githubusercontent.com/33194443/226116292-7326657b-ca85-47aa-9c7d-22e84b328b87.png)

https://github.com/PINTO0309/onnx2tf/releases/tag/1.7.31

- `RandomNormalLike`, `RandomUniformLike`
  - Improved stability of `RandomNormalLike` and `RandomUniformLike`
- `Split`
  - Suppression of `FlexSplitV` generation
- https://github.com/isletennos/MMVC_Trainer
- `D_180000.onnx`
- `G_180000.onnx`

```
pip install onnx2tf -U
onnx2tf -i D_180000.onnx -ois specs:1,257,100 -cotof -cotoa 1e-1
```
![image](https://user-images.githubusercontent.com/33194443/226115641-90c2ba82-a9e0-45b1-8a29-195f9fff0ff8.png)

**Comment by PINTO0309** [comment]
I'm glad to hear that it has been resolved. I'll close this issue then.
