### ISSUE TITLE
[NanoDet-plus] Load converted tensorflow model error

### ISSUE THREAD

**Issue by vuongnp** [PINTO0309/onnx2tf#261]
### Issue Type

Others

### onnx2tf version number

1.7.34

### onnx version number

1.13.1

### tensorflow version number

2.10.0

### Download URL for ONNX

https://drive.google.com/file/d/1Aak2FC9perpnNO_t7Ir1wG1vNXVt0CYj/view?usp=sharing

### Parameter Replacement JSON

```json
No
```

### Description

1. Personal development. This problem solving will help me develop a more powerful application in terms of performance.
2. I have a ONNX model converted from Pytorch, then I convert it to Tensorflow using onnx2tf. But I cannot load the converted Tensorflow model after converting from ONNX. This log:
```
  File "tools/MCT_PTQ_keras.py", line 96, in <module>
    model = tf.keras.models.load_model(args.model)
  File "/opt/conda/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 590, in _ExtractInputsAndAttrs
    raise TypeError(
TypeError: Exception encountered when calling layer "tf.math.multiply_5" (type TFOpLambda).

Input 'y' of 'Mul' Op has type int64 that does not match type int32 of argument 'x'.

Call arguments received by layer "tf.math.multiply_5" (type TFOpLambda):
  • x=tf.Tensor(shape=(), dtype=int32)
  • y=tf.Tensor(shape=(), dtype=int64)
  • name=None
```
3. I have tried other versions of onnx2tf/tensorflow
4. I need the tensorflow model to do something else

**Comment by vuongnp** [comment]
I already used onnx2tf v1.7.34

**Comment by PINTO0309** [comment]
If possible, I would like to know all the options you used for the conversion, etc.

```
onnx2tf -i model.onnx -osd
```

```
imported = tf.saved_model.load('saved_model')
f = imported.signatures["serving_default"]
```

**Comment by vuongnp** [comment]
To convert, I used:
```
onnx2tf -i model.onnx -oh5
```
To load, I used:
```
model = tf.keras.models.load_model("saved_model/model_float32.h5")
```

**Comment by PINTO0309** [comment]
I have just started looking into the cause, but for some reason the error seems to occur before or after this `Mul`. A little trial and error.

![image](https://user-images.githubusercontent.com/33194443/226876017-10776106-500d-4133-841b-0d5299ab2b0a.png)

**Comment by vuongnp** [comment]
Wow! I tried to find multiply_5 but I can't. Do you have any way to solve it?

**Comment by PINTO0309** [comment]
I displayed .h5 in Netron and used `Ctrl + F` to search the entire model. I took some detours to come up with this method.
![image](https://user-images.githubusercontent.com/33194443/226887590-74581ec5-d28e-474a-834a-9b12e93068e2.png)

**Comment by PINTO0309** [comment]
I have even identified the logic involved, but so far I have no idea why the error occurs.

![image](https://user-images.githubusercontent.com/33194443/226889287-6320430a-0a20-4b10-9f5d-af5814b5ae6d.png)

```
cond
<tf.Tensor: shape=(), dtype=int64, numpy=0>

tf.shape(input_tensor, out_type=out_dtype)[axis]
<KerasTensor: shape=() dtype=int64 (created by layer 'tf.__operators__.getitem_2')>

plus_values
<KerasTensor: shape=() dtype=int64 (created by layer 'tf.math.multiply_5')>
```

**Comment by PINTO0309** [comment]
The problem goes away when the last pull request is imported.

**Comment by vuongnp** [comment]
Nice. Please let me know when you have a new version. Thanks a lot!

**Comment by PINTO0309** [comment]
By the way, do you have an official name for this model? If so, I would like to add it to the title of the issue.

**Comment by vuongnp** [comment]
This original of model is NanoDet-Plus, but I am trying to modify the forward function for a deployment purpose.
NanoDet-Plus github: https://github.com/RangiLyu/nanodet

**Comment by PINTO0309** [comment]
Deployment of the latest version is finished. Please try it out.

Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.8.0

```
pip install onnx2tf -U

onnx2tf -i model.onnx -oh5
```
```python
import tensorflow as tf
model = tf.keras.models.load_model("saved_model/model_float32.h5")

# No-Error
```

**Comment by vuongnp** [comment]
It can be loaded. Thank you.
