### ISSUE TITLE
Problem with the docker image

### ISSUE THREAD

**Issue by triptec** [PINTO0309/onnx2tf#30]
### Issue Type

Others

### onnx2tf version number

1.1.38

### Download URL for ONNX

none

### Parameter Replacement JSON

```json
none
```

### Description

1. Personal dev
2. While trying to run the docker image with ```docker run --rm -it -v `pwd`:/workdir -w /workdir ghcr.io/pinto0309/onnx2tf:1.1.38``` I get the following error:
```
Unable to find image 'ghcr.io/pinto0309/onnx2tf:1.1.38' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/pinto0309/onnx2tf/manifests/1.1.38": unauthorized.
```
3. I'm considering building it myself
4. I just would like the documentation to be correct
5. None

Also I wonder what would be the best way to then go from tensorflow to tflite?

**Comment by PINTO0309** [comment]
I changed the package reference settings. Can you try running the same command again?

```bash
$ docker run --rm -it -v `pwd`:/workdir -w /workdir ghcr.io/pinto0309/onnx2tf:1.1.38

Unable to find image 'ghcr.io/pinto0309/onnx2tf:1.1.38' locally
1.1.38: Pulling from pinto0309/onnx2tf
675920708c8b: Already exists 
075b4fcec510: Pull complete 
678639269fac: Pull complete 
2025100f1a19: Pull complete 
afbf1df8c17d: Pull complete 
f885c455cad9: Pull complete 
af02cef1d6d0: Pull complete 
Digest: sha256:4c76aac5c7e1be62085a2d5f5c7dbbd884c2e02f65086f5772df19b1cec3bcf5
Status: Downloaded newer image for ghcr.io/pinto0309/onnx2tf:1.1.38

user@85b810172804:/workdir$ 
```

**Comment by triptec** [comment]
It works, thank you
