### ISSUE TITLE
Several problems when INT8-quantizing with calibration data

### ISSUE THREAD

**Issue by mikel-brostrom** [PINTO0309/onnx2tf#339]
### Issue Type

Bug

### onnx2tf version number

1.10.1

### onnx version number

1.13.1

### onnxruntime version number

1.14.1

### onnxsim (onnx_simplifier) version number

0.4.19

### tensorflow version number

2.12.0

### Download URL for ONNX

N/A

### Parameter Replacement JSON

```json
N/A
```

### Description

The only way of getting -cind to accept arguments is with the following format:

`-cind "{args.input}" "{calib_path}" "[[[[0, 0, 0]]]]" "[[[[1, 1, 1]]]]"`

This:

`-cind {args.input} {calib_path} "[[[[0, 0, 0]]]]" "[[[[1, 1, 1]]]]"`

 (what I used in `1.8.1`) does not work anymore. It has not been updated in the README.

Something else that does not work anymore is the calibration in the quantization process. This is how I generate the calibration data:

```python
def gen_calib_data(train_img_dir, nr_calib_imgs, img_size, out='calib_data.npy'):
    # reference:
    # https://github.com/PINTO0309/onnx2tf#7-calibration-data-creation-for-int8-quantization

    img_paths = glob.glob(os.path.join(train_img_dir, '*'))
    img_paths.sort()

    assert len(img_paths) >= nr_calib_imgs

    random.seed(0)
    random.shuffle(img_paths)

    calib_data = []
    for i, img_path in enumerate(img_paths):
        if i >= nr_calib_imgs:
            break
        img = cv2.imread(img_path)
        h, w, c = img.shape
        img, _ = preprocess(img, img_size)
        img = np.transpose(img, (1, 2, 0))
        img = img[np.newaxis]
        calib_data.append(img)
    calib_data = np.vstack(calib_data)  # [nr_calib_imgs, img_size[0], img_size[1], 3]
    np.save(file=out, arr=calib_data)
    logger.info(f'calib data generated with shape: {calib_data.shape}')
    return out
```

the generated `.npy` file has the following shape` [nr_imgs, w, h, 3]`. I get the following error:

```bash
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 0 Got: 8 Expected: 1
```

this was not the behavior with `1.8.1`. I feel that the documentation is not up to date as I cannot figure out the way to solve this by following it.

**Comment by PINTO0309** [comment]
Sorry. I will fix it right away tomorrow.

**Comment by mikel-brostrom** [comment]
Thank you for your quick answer @PINTO0309! Let me know when it is fixed so that I can try it out again :smile:

**Comment by PINTO0309** [comment]
I fixed it anyway, so please try it.
https://github.com/PINTO0309/onnx2tf/releases/tag/1.10.2

**Comment by mikel-brostrom** [comment]
Nice. Quantization works again with `.npy` calibration data file other than shape `[1, w, h, 3]`. And README is updated :rocket:

**Comment by mikel-brostrom** [comment]
Hmm, something is not completely right yet. My export command:

```bash
onnx2tf -i yolox_nano_ti_axera.onnx -o saved_model -nuo --non_verbose -oiqt -qt per-tensor -cind "images" "calib_data.npy" [[[[0, 0, 0]]]] [[[[1, 1, 1]]]]
```

the error:

```bash
ERROR: '-cind' option must have INPUT_NAME, NUMPY_FILE_PATH, MEAN(optional), STD(optional)
```

Any idea what this can be due to?

**Comment by mikel-brostrom** [comment]
Nm, got confused by the README again.

**Comment by mikel-brostrom** [comment]
This is still valid:

```
-cind "{args.input}" "{calib_path}" "[[[[0, 0, 0]]]]" "[[[[1, 1, 1]]]]"
```

**Comment by mikel-brostrom** [comment]
https://github.com/PINTO0309/onnx2tf/pull/341
