### ISSUE TITLE
[Yolov7] Yolov7 problem with detection coordinates

### ISSUE THREAD

**Issue by triptec** [PINTO0309/onnx2tf#34]
### Issue Type

Others

### onnx2tf version number

1.1.38

### Download URL for ONNX

https://github.com/triptec/detection-models/blob/master/yolov7/yolov7-tiny.onnx

### Parameter Replacement JSON

```json
{}
```

### Description

1. Personal project
2. I'm trying to convert a yolov7-tiny.onnx to a tflite int8 model.
First I export to onnx with:
```python export.py --weights ../models/yolov7/yolov7-tiny.pt --grid --simplify```
Then convert it with:
```onnx2tf -i yolov7-tiny.onnx -ioqd uint8 -oiqt```
Finaly I run (using https://github.com/ultralytics/yolov5/blob/master/detect.py)
```python detect.py --weights ../models/yolov7/yolov7-tiny.tflite --conf 0.25 --img-size 640 --source data/images/zidane.jpg```

And it results in this:
```
tensor([2.39083e+05, 1.02942e+05, 3.69536e+05, 3.17344e+05, 7.92245e-01, 0.00000e+00])
tensor([1.40084e+05, 2.27828e+05, 1.72367e+05, 3.18328e+05, 5.62911e-01, 2.70000e+01])
tensor([4.15838e+04, 1.53934e+05, 3.06103e+05, 3.16576e+05, 5.42062e-01, 0.00000e+00])
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.54206) tensor(0.)
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.56291) tensor(27.)
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.79225) tensor(0.)
image 1/1 /home/andreas/Development/priv/cat-detection/yolov5/data/images/zidane.jpg: 640x640 2 persons, 1 tie, 1561.9ms
Speed: 2.7ms pre-process, 1561.9ms inference, 1.6ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp38
```
As you can see it finds 2 people and 1 tie but the coordinates are not correct.

Here's the correct result with the onnx model:
![zidane](https://user-images.githubusercontent.com/240159/205175688-b84c70f3-1658-4fcd-8e39-1391a4a7cbd8.jpg)

In the readme it's stated that YOLOv7-tiny with Post-Process (NMS) ONNX to TFLite Float32 has been converted. Do you have the command and a "detection.py" what works with the result? Perhaps if I could get a hold of that I could solve this myself?

3. I've tried different flags when converting but I really don't know if this is due to the model not beiung compatible with int8.
4. I'm trying to convert a yolov7 model to tflite to be able to run inference on something called frigate and I've already written the infra to run yolov5 tflite models and would like to use the same code for yolov7, or with some changes but I need to figure out what to change.
5. none

**Comment by PINTO0309** [comment]
I generated a Float32 TFLite and checked the value of the final output and found inconsistencies, so I debugged and fixed the `MaxPool` bug. https://github.com/PINTO0309/onnx2tf/pull/35

https://github.com/PINTO0309/onnx2tf/releases/tag/1.1.46

I have compared .tflite converted with other tools to the modified model converted using onnx2tf and the output appears to match. Note that the accuracy degradation due to INT8 quantization is not taken into account.
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import numpy as np
from pprint import pprint
np.random.seed(0)

import cv2

dummy_input = cv2.imread('zidane.jpg')
dummy_input = cv2.resize(dummy_input, [640,640])
dummy_input = dummy_input.astype(np.float32)[np.newaxis, ...]

# onnx2tf
interpreter = tf.lite.Interpreter('onnx2tf/saved_model/model_float32.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], dummy_input)
interpreter.invoke()
ret1 = interpreter.get_tensor(output_details[0]['index'])
pprint(ret1)

# Float32
interpreter = tf.lite.Interpreter('onnx2tf/saved_model/yolov7-tiny.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], dummy_input)
interpreter.invoke()
ret2 = interpreter.get_tensor(output_details[0]['index'])
pprint(ret2)

ret2 = ret2.transpose(0,2,1)

print(f'total ret1: {ret1.flatten().shape}, ret2: {ret2.flatten().shape}')
print(f'total isclose ret1-ret2: {np.isclose(ret1.flatten(), ret2.flatten()).all()}')
```
```
total ret1: (2142000,), ret2: (2142000,)
total isclose ret1-ret2: True
```
