### ISSUE TITLE
Batched GRU layer fails during conversion

### ISSUE THREAD

**Issue by russellmcc** [PINTO0309/onnx2tf#346]
### Issue Type

Others

### onnx2tf version number

1.11.0

### onnx version number

1.14.0

### onnxruntime version number

1.13.1

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.12.0

### Download URL for ONNX

https://www.dropbox.com/s/sky10yunwgmc15g/batch_gru.onnx?dl=1

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose: exploring using this tool to convert onnx files to tflite files.
2. What: when running `onnx2tf -i batch_gru.onnx` on a onnx file that contains a batched GRU layer, the following error occurs:

```
INFO: onnx_op_type: Transpose onnx_op_name: /Transpose
INFO:  input_name.1: x shape: [17, 1, 64] dtype: float32
INFO:  output_name.1: /Transpose_output_0 shape: [1, 17, 64] dtype: float32
INFO: tf_op_type: transpose_v2
INFO:  input.1.a: name: x shape: (17, 64, 1) dtype: <dtype: 'float32'> 
INFO:  input.2.perm: val: [2, 0, 1] 
INFO:  output.1.output: name: tf.compat.v1.transpose/transpose:0 shape: (1, 17, 64) dtype: <dtype: 'float32'> 

INFO: onnx_op_type: GRU onnx_op_name: /GRU
INFO:  input_name.1: /Transpose_output_0 shape: [1, 17, 64] dtype: float32
INFO:  input_name.2: onnx::GRU_89 shape: [1, 384, 64] dtype: <class 'numpy.float32'>
INFO:  input_name.3: onnx::GRU_90 shape: [1, 384, 128] dtype: <class 'numpy.float32'>
INFO:  input_name.4: onnx::GRU_91 shape: [1, 768] dtype: <class 'numpy.float32'>
INFO:  input_name.5:  shape: None dtype: None
INFO:  input_name.6: state shape: [1, 17, 128] dtype: float32
INFO:  output_name.1: /GRU_output_0 shape: [1, 1, 17, 128] dtype: float32
INFO:  output_name.2: state_out shape: [1, 17, 128] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 282, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 360, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/onnx2tf/utils/common_functions.py", line 51, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/onnx2tf/ops/GRU.py", line 747, in make_node
    output, hidden_state = forward_lstm(X, initial_state=forward_initial_state) # [2,5,3], [2, 4]
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1044, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/onnx2tf/ops/GRU.py", line 364, in call
    outputs, h = self.rnn(inputs, initial_state=initial_state)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/keras/layers/rnn/base_rnn.py", line 615, in __call__
    output = super().__call__(full_input, **kwargs)
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/rmcclellan/Library/Caches/pypoetry/virtualenvs/streaming-trunet-eT2pQ-ST-py3.9/lib/python3.9/site-packages/keras/layers/rnn/base_rnn.py", line 520, in _validate_state_spec
    raise validation_error
ValueError: An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=ListWrapper([InputSpec(shape=(128, 17), ndim=2)]); however `cell.state_size` is [128]
ERROR: input_onnx_file_path: batch_gru.onnx
ERROR: onnx_op_name: /GRU
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

3. How: I have not attempted to solve this yet myself.  My next step is to read the code of `onnx2tf`.
4. Why: I want to use batch mode for the GRU layer
5. Resources:  The original pytorch model used to create the onnx file was this:

```
GRU = torch.nn.GRU(
    64,
    128,
    batch_first=True,
    bidirectional=False,
    num_layers=1,
)
```

**Comment by russellmcc** [comment]
Passing `-kat "state"` gets past this particular error - should this be necessary?

**Comment by russellmcc** [comment]
Additionally, I needed to use the parameter replacement json to fix the axis annotation on the `squeeze` parameter:

```
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/Squeeze",
      "param_target": "attributes",
      "param_name": "axes",
      "values": [1]
    }
  ]
}
```

This makes sense to me since the ONNX output before the squeeze is not in NCHW format.  I still feel that it would be convenient if `onnx2tf` could figure out that the state input to `GRU` does not need any transposition

**Comment by PINTO0309** [comment]
> Passing -kat "state" gets past this particular error - should this be necessary?

Yes. Unfortunately, it absolutely must be specified. This is because the tool does not know the meaning of the input data and cannot strictly determine whether it is `NCW`, `NHW`, `NHC`, `[seq_length, batch_size, input_size]`, or `[batch_size, seq_length, input_size]` just from the ONNX model structure. From the tool's point of view, the ONNX input appears to be simply data of some kind in three dimensions. This works the same for both onnx-tensorflow and tensorflow-onnx, just with different names for the options you specify.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/95564200-c3a1-43c0-8879-ec794426f1ac)

> This makes sense to me since the ONNX output before the squeeze is not in NCHW format. I still feel that it would be convenient if onnx2tf could figure out that the state input to GRU does not need any transposition

I was aware of your point when I implemented the `GRU`. I haven't come up with a good idea at the moment on how to determine this, since there are an infinite number of combinations of structures in the model. In the case of multiple OPs connected in a chain of beads, onnx2tf inherits the input/output structure information of the most recent OP to the subsequent OPs as much as possible, but in the case of a single OP (`GRU` only, as in this case), there is significantly insufficient information to determine the tensor's dimensionality. 

If you have any good ideas, I would be very happy to have your help in discussing them here.
It's not easy, though, as the NCHW to NHWC dimensional transposition implements quite a few tricks to keep it from breaking down. :disappointed:

**Comment by russellmcc** [comment]
I have no great ideas here, thank you for your explanation!  Perhaps there could be some mechanism to propagate the meaning of the tensor “backwards” from the gru node since we know that in the onnx model the state input has [direction, batch, hidden] dimensions.  This seems like a big change and I have no idea  how to do it :).  I’ll close the issue, thanks again for the explanation!
