### ISSUE TITLE
Support 5D input for operator Resize

### ISSUE THREAD

**Issue by nguyencse** [PINTO0309/onnx2tf#362]
### Issue Type

Documentation Feature Request

### onnx2tf version number

1.11.11

### onnx version number

1.31.1

### onnxruntime version number

None

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

None

### Parameter Replacement JSON

```json
None
```

### Description

```
ValueError: Exception encountered when calling layer “tf.image.resize” (type TFOpLambda).
‘images’ must have either 3 or 4 dimensions.
Call arguments received by layer “tf.image.resize” (type TFOpLambda):
  • images=tf.Tensor(shape=(1, 202, 12, 12, 64), dtype=float32)
  • size=[‘12’, ‘12’]
  • method=‘nearest’
  • preserve_aspect_ratio=False
  • antialias=False
  • name=‘/decoder1/decoder1.1/Resize’
ERROR: input_onnx_file_path: output_model.onnx
ERROR: onnx_op_name: /decoder1/decoder1.1/Resize
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

How can I deal with it? Input 5D for Resize Op haven't implemented yet, isn't it? Thank you for your recommendation

**Comment by PINTO0309** [comment]
Please share ONNX files.

I believe I have already addressed 5D Resize in the early stages of development, but there seems to be a mistake in the judging conditions.

**Comment by nguyencse** [comment]
Thanks for your answer @PINTO0309 .

I investigated to your source and realized that 5D just support for opset <= 17 by the code below of Resize Operator
`elif coordinate_transformation_mode == "asymmetric" and opset <= 17:` and so on.

So I changed the opset when converting my model from Pytorch to ONNX down to 17 (because in the previous code, I used opset 18).

I will to tell you the result later.

Thanks for your supporting

**Comment by nguyencse** [comment]
INFO: onnx_op_type: Resize onnx_op_name: /decoder1/decoder1.1/Resize
INFO:  input_name.1: /decoder1/decoder1.0/back/Transpose_output_0 shape: [1, 64, 202, 12, 12] dtype: float32
INFO:  input_name.2:  shape: None dtype: None
INFO:  input_name.3: /decoder1/decoder1.1/Constant_output_0 shape: [5] dtype: <class 'numpy.float32'>
INFO:  output_name.1: /decoder1/decoder1.1/Resize_output_0 shape: [1, 64, 404, 12, 12] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 282, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 360, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 51, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/ops/Resize.py", line 407, in make_node
    resized_tensor = Lambda(
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 1111, in upsampling3d_nearest
    d = new_size.shape[0]
AttributeError: Exception encountered when calling layer "lambda" (type Lambda).

'list' object has no attribute 'shape'

Call arguments received by layer "lambda" (type Lambda):
  • inputs=tf.Tensor(shape=(1, 202, 12, 12, 64), dtype=float32)
  • mask=None
  • training=None

**Comment by nguyencse** [comment]
I'm so sorry because I cannot share my model due to policy @PINTO0309

**Comment by PINTO0309** [comment]
`[1, 202, 12, 12, 64]` is decomposed into 202 2D Resizes. TensorFlow does not have a function to Resize a 3D tensor.

Note that modifying the logic does not guarantee anything, as it cannot be tested.

**Comment by nguyencse** [comment]
omg 👍 I just clone your source and add 1 commit to fix the shape just like you, but you did it first, lol @PINTO0309

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.12.1

**Comment by nguyencse** [comment]
so we have another issue here @PINTO0309 

`INFO: onnx_op_type: Resize onnx_op_name: /decoder1/decoder1.1/Resize
INFO:  input_name.1: /decoder1/decoder1.0/back/Transpose_output_0 shape: [1, 64, 202, 12, 12] dtype: float32
INFO:  input_name.2:  shape: None dtype: None
INFO:  input_name.3: /decoder1/decoder1.1/Constant_output_0 shape: [5] dtype: <class 'numpy.float32'>
INFO:  output_name.1: /decoder1/decoder1.1/Resize_output_0 shape: [1, 64, 404, 12, 12] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 282, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 360, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 51, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/ops/Resize.py", line 407, in make_node
    resized_tensor = Lambda(
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/nguyenny/Library/Python/3.9/lib/python/site-packages/onnx2tf/utils/common_functions.py", line 1114, in upsampling3d_nearest
    w = new_size[2]
IndexError: Exception encountered when calling layer "lambda" (type Lambda).

list index out of range

Call arguments received by layer "lambda" (type Lambda):
  • inputs=tf.Tensor(shape=(1, 202, 12, 12, 64), dtype=float32)
  • mask=None
  • training=None`

**Comment by nguyencse** [comment]
I found this line makes error for input 5D of Resize Operator.

`
 numeric_bools = np.asarray([isinstance(graph_node_output.shape[-(idx+1)], int) for idx in range(input_tensor_rank-2)])
            if numeric_bools.all():
                new_size = graph_node_output.shape[-2:len(graph_node_output.shape)]
`
change -2 to `-len(numeric_bools)`

new_size = graph_node_output.shape[-len(numeric_bools):len(graph_node_output.shape)]`

Is it ok @PINTO0309 ?

**Comment by nguyencse** [comment]
Replace  `images=input_tensor` by `images=i` because it seems that you forgot to use the variable after unstack tensor input  @PINTO0309   and update the code like my previous code, so Resize operator should works

```
def upsampling3d_nearest(
    input_tensor,
    new_size,
    align_corners,
    half_pixel_centers,
    name,
):  
    d = new_size[0]
    h = new_size[1]
    w = new_size[2]

    # Dpeth (height x width)
    resized_list = []
    unstack_img_list = tf.unstack(input_tensor, axis=1)
    for i in unstack_img_list:
        resized_list.append(
            tf.compat.v1.image.resize_nearest_neighbor(
                # images=input_tensor,
                images=i,
                size=[h, w],
                align_corners=align_corners,
                half_pixel_centers=half_pixel_centers,
                name=name,
            )
        )
    stack_img_hw = tf.stack(resized_list, axis=1)
    # Width (depth x Height)
    resized_list = []
    unstack_img_list = tf.unstack(stack_img_hw, axis=3)
    for i in unstack_img_list:
        resized_list.append(
            tf.compat.v1.image.resize_nearest_neighbor(
                # images=input_tensor,
                images=i,
                size=[d, h],
                align_corners=align_corners,
                half_pixel_centers=half_pixel_centers,
                name=name,
            )
        )
    stack_img_dh = tf.stack(resized_list, axis=3)
    return stack_img_dh
```

**Comment by PINTO0309** [comment]
I maintain this tool as a hobby, not a job, and can't devote enough time to it during the day, so if you don't mind, could you issue a pull request?

**Comment by nguyencse** [comment]
sure, but as I said before, I don't have permission to push my branch to your repo. I can only create branch but it told me that I don't have permission to push

**Comment by PINTO0309** [comment]
The following procedure can be used.
1. Fork this repository.
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/dcd6fa82-b4c0-487e-9a1a-f142a895f9ad)
2. Clone the forked repository to your local.
    ```
    git clone https://github.com/nguyencse/onnx2tf
    ```
3. Create a new branch.
    ```
    git checkout -b fix_3dresizes
    ```
4. Modify the program.
5. Commit the fix and push it to your branch.
    ```
    git commit -m "Fix resizes"
    git push --all
    ```
6. Create a pull request.
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/4e902681-a78e-4103-b445-dfcd842ab8af)

**Comment by nguyencse** [comment]
Merged. Thanks for your help @PINTO0309
