### ISSUE TITLE
CREStereo conversion from onnx to tensorflow failed

### ISSUE THREAD

**Issue by babiking** [PINTO0309/onnx2tf#380]
### Issue Type

Others

### onnx2tf version number

1.13.5

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/284_CREStereo/non_tensorrt/resources_iter20.tar.gz"

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose - Personal Development
2. What - onnx2tf -i crestereo_init_iter20_480x640.onnx process killed accidently
3. How - I tested onnx2tf on resnet18-v1-7.onnx successfully to make sure the validity of my onnx2tf environment. I tried regenerate .onnx file from .pth file directly (pytorch checkpoint model file from repository https://github.com/ibaiGorordo/CREStereo-Pytorch), but still not worked.
4. Why - I wanna deploy CREStereo model on an specific ARM device, therefore a corresponding .tflite file is needed.
![image](https://github.com/PINTO0309/onnx2tf/assets/33562173/30268e86-32c7-4da1-b14c-0ed3634f5659)

**Comment by PINTO0309** [comment]
`killed` indicates that your PC is out of RAM. Since this model is super complex, it seems to consume quite a lot of RAM during conversion.

I have found that when converting this model I need a maximum of about `110GB` of RAM. My PC has 128GB of RAM so `killed` does not occur.
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/c432c524-ec5e-4cef-bc43-2c22523c804e)

Now let me show how redundant this model is.
```bash
ssc4onnx -if crestereo_init_iter20_480x640.onnx
```
There are `16,851` operations. In other words, the structure of the model is too large. This does not directly correlate with the size of the onnx file and the complexity of the structure.
```
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ OP Type                ┃ OPs        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Add                    │ 2060       │
│ AveragePool            │ 8          │
│ Cast                   │ 1000       │
│ Concat                 │ 403        │
│ Conv                   │ 546        │
│ Div                    │ 468        │
│ Einsum                 │ 66         │
│ Elu                    │ 44         │
│ Expand                 │ 480        │
│ Floor                  │ 200        │
│ Gather                 │ 206        │
│ GatherElements         │ 400        │
│ Greater                │ 400        │
│ InstanceNormalization  │ 19         │
│ Less                   │ 400        │
│ MatMul                 │ 132        │
│ Mul                    │ 2741       │
│ Neg                    │ 1          │
│ Pad                    │ 183        │
│ Pow                    │ 44         │
│ Reciprocal             │ 22         │
│ ReduceMean             │ 888        │
│ ReduceSum              │ 25         │
│ Relu                   │ 283        │
│ Reshape                │ 804        │
│ Resize                 │ 2          │
│ Sigmoid                │ 162        │
│ Slice                  │ 1440       │
│ Softmax                │ 3          │
│ Split                  │ 182        │
│ Sqrt                   │ 44         │
│ Sub                    │ 1128       │
│ Tanh                   │ 81         │
│ Transpose              │ 150        │
│ Unsqueeze              │ 1036       │
│ Where                  │ 800        │
│ ---------------------- │ ---------- │
│ Total number of OPs    │ 16851      │
│ ====================== │ ========== │
│ Model Size             │ 24.6MiB    │
└────────────────────────┴────────────┘
INFO: file: crestereo_init_iter20_480x640.onnx
INFO: producer: pytorch 1.11.0
INFO: opset: 12
INFO: input_name.1: left shape: [1, 3, 480, 640] dtype: float32
INFO: input_name.2: right shape: [1, 3, 480, 640] dtype: float32
INFO: output_name.1: output shape: [1, 2, 480, 640] dtype: float32
INFO: Finish!
```

**Comment by babiking** [comment]
hi, PINTO, great thanks to your prompt reply.

I re-deployed above mentioned onnx2tf environment (python) to another linux server with 128G RAM, and re-run the onnx2tf command. The "killed out of memory" does not occur but I have got some new troubles on mismatched tensor shapes.  Any suggestions?

![image](https://github.com/PINTO0309/onnx2tf/assets/33562173/82b5399e-aca5-4b3e-83c5-aea96a53a8e6)

**Comment by PINTO0309** [comment]
Try everything listed in the error message before you ask the question. I do not want to investigate this model.

**Comment by PINTO0309** [comment]
```
pip install -U onnx2tf
```
