### ISSUE TITLE
Conversion issue when trying to run model with Vx delegate

### ISSUE THREAD

**Issue by mafernandezGI** [PINTO0309/onnx2tf#381]
### Issue Type

Others

### onnx2tf version number

1.13.3

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

https://drive.google.com/file/d/1vg5dFV_NzJL4hh45bLybkGUX6IqA9F6c/view?usp=sharing

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose: Personal Development
2. What: When trying to run a model converted with the onnx2tf tool with a vx_delegate as the external delegate of the interpreter, the code outputs an error at the interpreter.Invoke() (ERROR: Failed to verify graph, more extensive error in the Pastebin down below). A model directly converted directly from onnx to tflite with the [eiQ toolkit](https://www.nxp.com/design/software/development-software/eiq-ml-development-environment/eiq-toolkit-for-end-to-end-model-development-and-deployment:EIQ-TOOLKIT) works with the vx_delegate, but the direct conversion adds intermediate transpose layers (NCHW vs NHWC issue) that reduce the inference speed.
3. How: Tried many different things, mainly related to the parameters of onn2tf. Currently using:  `onnx2tf -i monodepth_op15.onnx -osd`, but tried with `-kat`, `-coion`, and some others. 
5. Why: Converting the model with the onnx2tf tool allows for the removal of the transpose layers added in the direct conversion from onnx to tflite, which in turn improves speed. As an example, in the NXP documentation, they mention a similar case where the removal of the transpose layers improves the performance of the model from 13.20 ms to 3.61 ms. I understand that this might not be an appropriate issue for this repository, but wanted to open the issue just in case.
6. Resources: 

- [Converted tflite model with the transpose layers](https://drive.google.com/file/d/1NHRloDd4X71L6o-IE73fOKlvSvIOUcZl/view?usp=sharing). We converted this with the eiQ toolkit from the onnx posted above and also did the quantization with a relevant dataset. This one is **working on the NPU with the delegate**.
- [Converted tflite model without the transpose layers](https://drive.google.com/file/d/1qErcgTA7_wqkAXD-MhFYb9-JTnBiJhV3/view?usp=sharing): This model was first converted to tensorflow using the onnx2tf tool and then quantized with the eiQ tool, as suggested in the NXP documentation (in the NXP documentation, they suggested openvino2tensorflow tool, but that one was giving some problems). This model is **giving errors** (below). 
- In case it is useful, error when running the second tflite model (the one converted with onnx2tf) with the delegate: https://pastebin.com/31CK95vT

**Comment by PINTO0309** [comment]
- replace_monodepth_op15.json
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "/encoder/stage2/features.5/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.5/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.6/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.6/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.7/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.7/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.8/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.8/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.9/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.9/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.10/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.10/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      },
      {
        "op_name": "/encoder/stage2/features.11/Gather_1",
        "param_target": "outputs",
        "param_name": "/encoder/stage2/features.11/Gather_1_output_0",
        "post_process_transpose_perm": [0,2,3,1]
      }
    ]
  }
  ```
- convert
  ```
  onnx2tf -i monodepth_op15.onnx -cotof -prf replace_monodepth_op15.json
  ```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/f71b00d3-9769-45a8-a292-0022fe4da89f)

**Comment by PINTO0309** [comment]
If the logs show that the output is exactly the same between ONNX and TFLite, and the error still occurs on the delegate side, then it is clearly a bug in the delegate. The final output `Matches` means no errors.

- [monodepth_op15_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/11636881/monodepth_op15_float32.tflite.zip)
- [monodepth_op15_float16.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/11636887/monodepth_op15_float16.tflite.zip)
- [int8.zip](https://github.com/PINTO0309/onnx2tf/files/11636901/int8.zip)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.13.6

**Comment by PINTO0309** [comment]
Not that it matters, but if I were you, I would use `Split` instead of `Gather` to reduce the number of operations on the entire model. The `Gather` in this model is just noise overall.

```
Transpose: [2, 24, 9216]
Reshape  : [2, 24, 96, 96]
Split    : [1, 24, 96, 96], [1, 24, 96, 96]
Conv     : [1, 24, 96, 96]
    :
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/045023ee-9acf-4ac7-93a7-5163f14da132)

**Comment by mafernandezGI** [comment]
Updated to the latest version of onnx2tf, the final output indeed matches. I then quantize the tf model with eiQ Toolkit and the issue persist.  Also tried with the non-quantized tflite model.

I agree with you, the most probable cause at this point is something related to the tim-vx delegate.

I am still working on this issue, so I will post any updates.

Thank you very much for the quick response, have a nice day.

**Comment by mafernandezGI** [comment]
Thank you again for the response.

Is there a way to remove the gathers, change the reshape to [2, 24, 96, 96], and add the split with the onnx2tf tool?

**Comment by PINTO0309** [comment]
The tool only has the ability to generate models that are almost faithfully accurate, except that it optimizes the input onnx as much as possible.

I don't know how you generated this model, but if you are using PyTorch, just replace it with `torch.split` and then re-export to onnx.

**Comment by mafernandezGI** [comment]
I am using a pretrained model from the [TCMonodepth repository](https://github.com/yu-li/TCMonoDepth/blob/main/networks/TCSmallNet.py). 

Looking at it, it seems like line 66 is the relevant reshape:
`x = x.reshape(2, -1, num_channels // 2, height, width)`

**Comment by PINTO0309** [comment]
## 1. `Slice` pattern
This is the model structure that is least likely to cause problems in any SDK: it does not generate a 5-dimensional tensor.
```python
    def channel_shuffle(self, x):
        batchsize, num_channels, height, width = x.data.size()
        assert (num_channels % 4 == 0)
        x = x.reshape(batchsize * num_channels // 2, 2, height * width)
        x = x.permute(1, 0, 2)
        if batchsize > 1:
            x = x.reshape(2, -1, num_channels // 2, height, width)
            return x[0], x[1]
        else:
            x = x.reshape(2, num_channels // 2, height, width)
            return x[0:1], x[1:2]
```

- onnx
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/5d66c659-1359-4a45-88f1-211cb78f13c7)
- tflite
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/5cbb351c-b362-4547-9b8b-454c84c8ce45)

## 2. `Split` pattern
The model with the highest inference efficiency is shown below.
```python
    def channel_shuffle(self, x):
        batchsize, num_channels, height, width = x.data.size()
        assert (num_channels % 4 == 0)
        x = x.reshape(batchsize * num_channels // 2, 2, height * width)
        x = x.permute(1, 0, 2)
        if batchsize > 1:
            x = x.reshape(2, -1, num_channels // 2, height, width)
            return x[0], x[1]
        else:
            x = x.reshape(2, num_channels // 2, height, width)
            # return x[0:1], x[1:2]
            return torch.split(x, 1)
```
- onnx
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/b16ae89a-d545-41f1-9ffd-c9fde114837c)
- tflite
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/ddbd95e2-7757-49b6-b527-a1a228d26bf6)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/384_TCMonoDepth
