### ISSUE TITLE
[AnimeGANv3] onnx -> tflife conversion error

### ISSUE THREAD

**Issue by LirRence** [PINTO0309/onnx2tf#388]
### Issue Type

Others

### onnx2tf version number

1.13.10

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

https://github.com/TachibanaYoshino/AnimeGANv3/blob/master/AnimeGANv3/AnimeGANv3_JP_face_v1.0.onnx

### Parameter Replacement JSON

```json
I did not use this parameter replacement.
```

### Description

I'm trying to convert this onnx model to a tflite one, then proceed to use it in my mobile app cartoonizing.
Command I used to do the conversion:

`onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx`

First of all, I have little to no knowledge in ML so this is me basically trying my best to get the conversion worked. I've tried various parameters provided in the document but nothing worked and I got same errors every time. Sorry if it is offensively stupid but I attempted parameters replacement like these:

```
onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx -b 1
onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx
onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx -k AnimeGANv3_input_0
onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx -kt AnimeGANv3_input_0
onnx2tf -i AnimeGANv3_JP_face_v1.0.onnx -kat AnimeGANv3_input_0
```
**Error Log**
Everything seems to work fine except for these warnings and errors: 
```
WARNING: The optimization process for shape estimation WARNING: The optimization process for shape estimation is skipped because it contains OPs that cannot be inferred by the standard onnxruntime.
WARNING: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Conv node. Name:'generator/base/Conv_1/Conv2D:0_nchwc' Status Message: Invalid input shape: {2,2}
[...]
INFO: onnx_op_type: Upsample onnx_op_name: Upsample__195
INFO:  input_name.1: generator/main/External_attention/LeakyRelu:0 shape: None dtype: float32
INFO:  input_name.2: Concat__194:0 shape: [4] dtype: float32
INFO:  output_name.1: Upsample__195:0 shape: None dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\onnx2tf\utils\common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\onnx2tf\utils\common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\onnx2tf\utils\common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\onnx2tf\ops\Upsample.py", line 100, in make_node
    new_size = tf.cast(h_w_scale * tf.cast(h_w_shape, scales.dtype), tf.int32)
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\darsh\anaconda3\envs\onnx2tf_env\lib\site-packages\tensorflow\python\framework\constant_op.py", line 346, in _tensor_shape_tensor_conversion_function
    raise ValueError(
ValueError: Cannot convert a partially known TensorShape (None, None) to a Tensor.
ERROR: input_onnx_file_path: AnimeGANv3_JP_face_v1.0.onnx
ERROR: onnx_op_name: Upsample__195
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

```
**Other info**
I use Conda to set up the environment. It's Python 3.8 and I run this on Windows 11.

**Why I need this problem solved?**
Actually, the mobile app is not mine. I'm an utter newbie in an software developing company and they are developing a cartoonzing app. My Python is around beginner-intermediate level and there's literal no one in my company that's more experienced or familiar with Python other than me, so I got assigned this task. My leader need a tflite model to try out the app, to see how things work and insisting on me converting this AnimeGAN to a tflite. It's a week past and I really trust onnx2tf is the tool I need, but I cannot figure out how to use it properly.

Thanks in advance for your effort reading, reacting and helping me. I really appreciate that!

**Comment by PINTO0309** [comment]
First, please generate ONNX at NCHW. It is a hassle. It means that it is a hassle to give advice on every single individual case.
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/8db2691d-3b3d-4440-90e0-0365bf2c547a)

**Comment by LirRence** [comment]
Thanks for your reply! I'll try generating/finding an ONNX model in NCHW.

But what if I could not change anything to the existing AnimeGAN model? Does it mean that it will be a huge hassle for converting models that are not at NCHW?

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/simple-onnx-processing-tools

**Comment by LirRence** [comment]
Thanks! I will look into that.

**Comment by LirRence** [comment]
Hi PINTO. 

I've looked into your tools and used `scc4onnx ` to transpose my model from NHWC to NCHW.
Command I used: 
```
scc4onnx --input_onnx_file_path AnimeGANv3_JP_face_v1.0.onnx \
--output_onnx_file_path AnimeGANv3_JP_face_v1.0_ord.onnx \
--input_op_names_and_order_dims AnimeGANv3_input:0 [0,3,2,1]
```
It finished beautifully and gave me the output **AnimeGANv3_JP_face_v1.0_ord.onnx**.
Then I put that output into `onnx2tf ` but nothing changed... The error still persists.

Could you please guide me what to do next or where to look into to solve the problem? Thank you very much.

**Comment by PINTO0309** [comment]
[AnimeGANv3_JP_face_v1.0.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/11712298/AnimeGANv3_JP_face_v1.0.onnx.zip)

**Comment by LirRence** [comment]
Thanks for your handing the onnx file that works. I really appreciate that!
I'd be happy if you could provide some insights to how you did it.
