### ISSUE TITLE
Error in ConvTranspose conversion

### ISSUE THREAD

**Issue by doo5643** [PINTO0309/onnx2tf#389]
### Issue Type

Others

### onnx2tf version number

1.5.19

### onnx version number

1.12.0

### onnxruntime version number

1.13.1

### onnxsim (onnx_simplifier) version number

None

### tensorflow version number

2.11.0

### Download URL for ONNX

https://drive.google.com/file/d/1QrMJLkd2LzoGkLXnpLdgNljmQ5etBL9j/view?usp=sharing

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
      {
        "op_name": "/_up1/_up/ConvTranspose",
        "param_target": "outputs",
        "param_name": "/_up1/_up/ConvTranspose_output_0",
        "pre_process_transpose_perm": [0,3,1, 2]
      }
    ]
  }
```

### Description

1. Purpose: Personal development
2. What: What events are occurring? What error logs are being displayed? 
Attached. [UNet_error.txt](https://github.com/PINTO0309/onnx2tf/files/11716137/UNet_error.txt)

4. How: How did you attempt to solve the problem yourself?: By using `Parameter Replacement json`, I tried. But it does not solve the issue.
5. Why: Why do you need this problem solved? I am hoping to use the model in mobile devices. That s why I d like to figure out this sissue.
6. Resources: Material you have cited or referenced other than ONNX or JSON.

**Comment by PINTO0309** [comment]
```
onnx2tf -i UNET.onnx -ois input:1,3,224,224
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/cd599edd-fb07-4a03-b916-371995b7c05d)

**Comment by doo5643** [comment]
Thank you for your assistance.
