### ISSUE TITLE
[CNN_AUTOENCODER] Error in cnn autoencoder output value validation

### ISSUE THREAD

**Issue by doo5643** [PINTO0309/onnx2tf#394]
### Issue Type

Others

### onnx2tf version number

1.13.10

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

https://drive.google.com/file/d/1cSK9D8LVVpHDfLEPci-rqXmt-6I93-7G/view?usp=drive_link

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
      {
        "op_name": "/decoder/deconv_block1/deconv_block1.1/BatchNormalization",
        "param_target": "inputs",
        "param_name": "/decoder/deconv_block1/deconv_block1.0/ConvTranspose_output_0",
        "pre_process_transpose_perm": [0,2,1]
      },
      {
        "op_name": "/decoder/deconv_block2/deconv_block2.1/BatchNormalization",
        "param_target": "inputs",
        "param_name": "/decoder/deconv_block2/deconv_block2.0/ConvTranspose_output_0",
        "pre_process_transpose_perm": [0,2,1]
      }
    ]
}
```

### Description

1. Purpose: Personal development
2. What: Log is attached [out.log](https://github.com/PINTO0309/onnx2tf/files/11741863/out.log)
Executed command is `onnx2tf -i CNN_AUTOENCODER.onnx -prf cnn_autoencoder.json --output_signaturedefs -cotof`
3. How: Used parameter replacement json. The model conversion turns out ok, but in output value validation phase, it throws errors.
4. Why: To use the model inside mobile devices
5. Resources: None

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.13.11
