### ISSUE TITLE
`com.microsoft.GroupNorm` support for Stable Diffusion model support

### ISSUE THREAD

**Issue by senapatiashok** [PINTO0309/onnx2tf#401]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.13.1

### onnx version number

1.14.0

### onnxruntime version number

1.15

### onnxsim (onnx_simplifier) version number

latest

### tensorflow version number

2.13

### Download URL for ONNX

https://huggingface.co/axodoxian/stable_diffusion_onnx/tree/main/unet

### Parameter Replacement JSON

```json
{
    "format_version":1,
    "operations": [
        {"op_name":"GroupNormalization",
         "groups":32,
         "axis"=-1,
         "epsilon"=0.001,
         "center"=True,
         "scale"=True,
         "beta_initializer"="zeros",
         "gamma_initializer"="ones",
         "beta_regularizer"=None,
         "gamma_regularizer"=None,
         "beta_constraint"=None,
         "gamma_constraint"=None,
     ]
}
```

### Description

1. Purpose: Research - Trying to run the Stable Diffusion model on Mobile device on Samsung S23 using Tflite Delegate. This will enable to realize the end to end pipeline of usecase on mobile.

Post CPU/GPU evaluation of tflite, will check to port on further on DSP/NPU.

2. Conversion is failing due to GroupNormalization is not present in OnnxRuntime

3. GroupNormalization implementation done in tensorflowlite and keras model conversion works, but not aware how to add in ONNX, so asking here.

4. `com.microsoft.GroupNorm` support if added a whole paradigm shift will happen, as ONNX models will be used on Mobile devices with tflite delegate. 

5. KERAS, TensorflowLite, Huggingface Stable Diffusion 1.4

Note: adding this layer will solve to enable the GenAI models on Device, it will be a great contribution towards GenAI revolution.

**Comment by PINTO0309** [comment]
The operation you are expecting is precisely the `com.microsoft.GroupNorm` operation. Since this OP is non-standard for ONNX and designed independently by Microsoft, implementation is a low priority.

The same is true for `MultiHeadAttention`. It can be implemented, but is non-standard and has a low priority.

**Comment by senapatiashok** [comment]
Overwhelmed by your quick response and adding GN.

While converting I am getting below error.

>onn2tf -i model.onnx

>TypeError: Exception encountered when calling layer "tf.nn.convolution_2" (type TFOpLambda). Input 'filter' of 'Conv2D' Op has type float16 that does not match type float32 of argument 'input'.


Because model is having fp16 weights.

#note: weights is fp16 taken because fp32 model size 3.4 GB. Or we have separated fp32 models as model.onnx(51K) , weights.pb(3.4GB)

Is there any way we can pass model and weight separately for onnx2tf conversion.

Thank you for, support.

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/whisper-onnx-exporter

**Comment by senapatiashok** [comment]
Thank you for support.
Our onnx model is fp16.

And converting to tflite, it gives below error

ERROR: input_onnx_file_path: onnx-stable-diffusion-v1-5/unet/model.onnx ERROR: onnx_op_name: /ConstantOfShape ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again. ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option. ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.


 while running stable-diffusion FP32 onnx model 
we are getting this error
