### ISSUE TITLE
Fail to understand the GridSample error message

### ISSUE THREAD

**Issue by automan000** [PINTO0309/onnx2tf#402]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.13.12

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0rc0

### Download URL for ONNX

None

### Parameter Replacement JSON

```json
None
```

### Description

Hi, thanks for this great work.

I tried to use this tool to convert my own model but stuck on the conversion of GridSample. The original PyTorch model and converted ONNX model work properly. Here is the error message:

```
INFO: onnx_op_type: GridSample onnx_op_name: GridSample_37
INFO:  input_name.1: feat shape: [3757, 512, 50, 50] dtype: float32
INFO:  input_name.2: line_pooling1.line_grid shape: [3757, 8, 8, 2] dtype: <class 'numpy.float32'>
INFO:  output_name.1: onnx::Concat_89 shape: [3757, 512, 8, 8] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/gpu/research/onnx2tf-1.13.12/onnx2tf/utils/common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/gpu/research/onnx2tf-1.13.12/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/gpu/research/onnx2tf-1.13.12/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/gpu/research/onnx2tf-1.13.12/onnx2tf/ops/GridSample.py", line 478, in make_node
    final_reshape = tf.reshape(add63, shape=output_shape)
  File "/home/gpu/anaconda3/envs/onnx2tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/gpu/anaconda3/envs/onnx2tf/lib/python3.9/site-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/gpu/anaconda3/envs/onnx2tf/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.reshape_13" (type TFOpLambda).

Cannot reshape a tensor with 123109376 elements to shape [3757,512,8,2] (30777344 elements) for '{{node tf.reshape_13/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](Placeholder, tf.reshape_13/Reshape/shape)' with input shapes: [3757,512,64], [4] and with input tensors computed as partial shapes: input[1] = [3757,512,8,2].

Call arguments received by layer "tf.reshape_13" (type TFOpLambda):
  • tensor=tf.Tensor(shape=(3757, 512, 64), dtype=float32)
  • shape=['3757', '512', '8', '2']
  • name=None
```

I failed to understand this error message. Does it indicate that GridSample needs 123109376 elements but only get 30777344 elements? Could you please provide some possible reason for this error, since the corresponding ONNX model works properly.

**Comment by PINTO0309** [comment]
Somewhere in the OP before `GridSample`, the transposition operation failed.

Most of the error messages in this tool are simply errors displayed by either onnxruntime or TensorFlow itself. 
I will not do any research unless you share the onnx file with me by DM or any other means.

I am not a psychic.

**Comment by automan000** [comment]
Hi. Thanks for your quick reply. I need to find a place with better network condition, I will share the onnx file as soon as possible.

**Comment by PINTO0309** [comment]
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/08a1e9a5-dd5e-47a6-bded-52df1e373122)
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/2a7efd7d-a736-4078-9d8a-fc8dc95b431b)

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.14.2
