### ISSUE TITLE
Unable to Convert ONNX FP16 Model to TFLite

### ISSUE THREAD

**Issue by ThummalaPallavi** [PINTO0309/onnx2tf#410]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.14.0

### onnx version number

1.13.1

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.12.0

### Download URL for ONNX

https://huggingface.co/axodoxian/stable_diffusion_onnx/tree/main/unet

### Parameter Replacement JSON

```json
{

},
```

### Description

Research:

Hello, Im trying to convert the FP16 Onnx model present in https://huggingface.co/axodoxian/stable_diffusion_onnx/tree/main/unet
to TFLite. But the Onnx2tf tool is failing with below error.

TypeError: Exception encountered when calling layer "tf.nn.convolution_2" (type TFOpLambda).

Input 'filter' of 'Conv2D' Op has type float16 that does not match type float32 of argument 'input'.

Could you please help in resolving above issue?

Thanks in Advance,

**Comment by PINTO0309** [comment]
https://glaringlee.github.io/onnx.html#use-external-data-format
