### ISSUE TITLE
Error in tf.pad operation

### ISSUE THREAD

**Issue by RocketFlash** [PINTO0309/onnx2tf#413]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.14.3

### onnx version number

1.14.0

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.13.0

### Download URL for ONNX

https://drive.google.com/file/d/16gnu4denuK-jO03vKmB7P7PiGvBGrG14/view?usp=sharing

### Parameter Replacement JSON

```json
{}
```

### Description

I was trying to convert onnx model but conversion crashed on Pad operation

```
ValueError: Exception encountered when calling layer "tf.pad" (type TFOpLambda).

Shape must be rank 2 but is rank 1 for '{{node tf.pad/Pad}} = Pad[T=DT_FLOAT, Tpaddings=DT_INT32](Placeholder, tf.pad/Pad/paddings)' with input shapes: [?,170,170,3], [8].

Call arguments received by layer "tf.pad" (type TFOpLambda):
  • tensor=tf.Tensor(shape=(None, 170, 170, 3), dtype=float32)
  • paddings=tf.Tensor(shape=(8,), dtype=int32)
  • mode='constant'
  • constant_values=array(0., dtype=float32)
  • name='/backbone/conv_stem/Pad'
ERROR: input_onnx_file_path: arcface_tf_efficientnetv2_b1.in1k_im170_emb512.onnx
ERROR: onnx_op_name: /backbone/conv_stem/Pad
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

Inference in onnxruntime outputs data as expected, input type and shape : type: float32[batch_size,3,170,170]
Could you help me to understand what I am doing wrong?

**Comment by PINTO0309** [comment]
Please upgrade onnxsim to 0.4.33. Although it is a very specific pattern, we have found that using 0.4.17 in your model results in insufficient optimization of constants, which interferes with model conversions.

I would change the version of onnxsim that this tool assumes to 0.4.33.

```
pip install -U onnxsim==0.4.33

onnx2tf -i model.onnx -b 1
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/9ce69a14-5687-4afd-8ce8-032e693c5151)

**Comment by RocketFlash** [comment]
It helped, thank you very much!

**Comment by PINTO0309** [comment]
Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.14.4
