### ISSUE TITLE
Unable to Convert ONNX FP16 Model to TFLite

### ISSUE THREAD

**Issue by akshatshah17** [PINTO0309/onnx2tf#415]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.14.3

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.17

### tensorflow version number

2.12.0

### Download URL for ONNX

https://github.com/PINTO0309/onnx2tf

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "/box_pooler/Concat",
      "param_target": "outputs",
      "param_name": "/box_pooler/Concat_output_0",
      "post_process_transpose_perm": [1,0]
    }
  ]
}
```

### Description

Research:

Hello, I am trying to convert the FP32 Onnx model to tflite, but due to error it's failing, this are the images of the block which is failing.

![Screenshot (184)](https://github.com/PINTO0309/onnx2tf/assets/63163976/d1583080-432c-4d9c-89aa-44887e8bcf61)
![Screenshot (185)](https://github.com/PINTO0309/onnx2tf/assets/63163976/f5b64927-5cc4-4de6-bdef-68a5e6a125aa)
![Screenshot (186)](https://github.com/PINTO0309/onnx2tf/assets/63163976/74babc89-8f66-4883-adc1-47df139ed764)
![Screenshot (187)](https://github.com/PINTO0309/onnx2tf/assets/63163976/e1dd7e1d-c07b-48e7-b560-c9812f75f9a3)

Here is the error while running the model I have tried to use json file also but failing

INFO: onnx_op_type: Concat onnx_op_name: /box_pooler/Concat_1
INFO:  input_name.1: /box_pooler/Cast_output_0 shape: [300, 1] dtype: float32
INFO:  input_name.2: /Gather_output_0 shape: [300, 4] dtype: float32
INFO:  output_name.1: /box_pooler/Concat_1_output_0 shape: [300, 5] dtype: float32
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/code/onnx2tf/onnx2tf/utils/common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/code/onnx2tf/onnx2tf/utils/common_functions.py", line 361, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/home/code/onnx2tf/onnx2tf/utils/common_functions.py", line 52, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/home/code/onnx2tf/onnx2tf/ops/Concat.py", line 164, in make_node
    tf.concat(
  File "/home/code/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/code/.local/lib/python3.8/site-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/code/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.concat" (type TFOpLambda).

Dimension 0 in both shapes must be equal, but are 300 and 4. Shapes are [300] and [4]. for '{{node tf.concat/concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](tf.concat/concat/values_0, Placeholder, tf.concat/concat/axis)' with input shapes: [300,1], [4,300], [] and with computed input tensors: input[2] = <1>.

Call arguments received by layer "tf.concat" (type TFOpLambda):
  • values=['tf.Tensor(shape=(300, 1), dtype=float32)', 'tf.Tensor(shape=(4, 300), dtype=float32)']
  • axis=1
  • name='/box_pooler/Concat_1'
ERROR: input_onnx_file_path: aig_detector_cnn_2706.onnx
ERROR: onnx_op_name: /box_pooler/Concat_1
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

Could you please help in resolving above issue?

Thanks in Advance,

**Comment by PINTO0309** [comment]
Please share your onnx files with us. Otherwise I will not do any investigation.
