### ISSUE TITLE
Unable to install process in google colab

### ISSUE THREAD

**Issue by joh9911** [PINTO0309/onnx2tf#416]
### Issue Type

Others

### OS

Windows

### onnx2tf version number

1.14.4

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

my local

### Parameter Replacement JSON

```json
.
```

### Description

1. Personal
2. I tried to install on the description in Goole Colab

```
!sudo add-apt-repository -y ppa:deadsnakes/ppa
!sudo apt-get -y update
!sudo apt-get -y install python3.9
!sudo apt-get -y install python3.9-dev
!sudo apt-get -y install python3-pip
!sudo apt-get -y install python3.9-distutils
!wget https://github.com/PINTO0309/onnx2tf/releases/download/1.7.3/flatc.tar.gz \
  && tar -zxvf flatc.tar.gz \
  && sudo chmod +x flatc \
  && sudo mv flatc /usr/bin/
!python3.9 -m pip install -U setuptools \
  && python3.9 -m pip install -U pip \
  && python3.9 -m pip install -U distlib
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
!python3.9 -m pip install tensorflow==2.13.0 \
  && python3.9 -m pip install -U onnx==1.13.1 \
  && python3.9 -m pip install -U nvidia-pyindex \
  && python3.9 -m pip install -U onnx-graphsurgeon \
  && python3.9 -m pip install -U onnxruntime==1.15.0 \
  && python3.9 -m pip install -U onnxsim==0.4.33 \
  && python3.9 -m pip install -U simple_onnx_processing_tools \
  && python3.9 -m pip install -U onnx2tf \
  && python3.9 -m pip install -U protobuf==3.20.3 \
  && python3.9 -m pip install -U h5py==3.7.0 \
  && python3.9 -m pip install -U psutil==5.9.5
```
  
  and there was an error
  
  `Requirement already satisfied: nvidia-pyindex in /usr/local/lib/python3.9/dist-packages (1.0.9)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting onnx-graphsurgeon
  Using cached onnx-graphsurgeon-0.0.1.dev5.tar.gz (7.9 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

I might be unfamiliar with the issue due to my lack of experience. I apologize for any inconvenience caused

**Comment by PINTO0309** [comment]
It seems that the OS version of the Goole Colab backend has been upgraded to Ub untu22.04, and the previous installation sequence was causing errors. I would modify the README as follows
```
!sudo apt-get -y update
!sudo apt-get -y install python3-pip
!sudo apt-get -y install python-is-python3
!wget https://github.com/PINTO0309/onnx2tf/releases/download/1.7.3/flatc.tar.gz \
  && tar -zxvf flatc.tar.gz \
  && sudo chmod +x flatc \
  && sudo mv flatc /usr/bin/
!pip install -U pip \
  && pip install tensorflow==2.13.0 \
  && pip install -U onnx==1.13.1 \
  && python -m pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com \
  && pip install -U onnxruntime==1.15.0 \
  && pip install -U onnxsim==0.4.33 \
  && pip install -U simple_onnx_processing_tools \
  && pip install -U onnx2tf \
  && pip install -U protobuf==3.20.3 \
  && pip install -U h5py==3.7.0 \
  && pip install -U psutil==5.9.5
```
