### ISSUE TITLE
Batched GridSample results in surprisingly large TFLite models

### ISSUE THREAD

**Issue by jpowie01** [PINTO0309/onnx2tf#426]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.14.7

### onnx version number

1.13.1

### onnxruntime version number

1.15.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

Generated in the reproduction script down below.

### Parameter Replacement JSON

```json
n/a
```

### Description

Hello,
I'm seeing a rather strange behaviour of Grid Sampling operation in the output TF Lite model whenever Grid Sampling has to be run on larger batch sizes. The resulting model size seems to grow linearly with the size of the batch defined in the model. In my case, both grid sampling's input tensors are passed as an input to the model, so they shouldn't result in any extra weights saved in the output model graph.

Have you ever seen such a problem before? What can be causing this issue? Am I missing some parameters replacement or extra flags to the converter? Or could it be a bug in TensorFlow / TensorFlow Lite?

Sadly, I can't lower the batch size down to 1 as the example down below is a stripped-out operation from a bigger model that has to run the grid sampling on those specific tensor shapes.

Thank you for your help and hard work on this super useful tool! 🙏 

### Reproduction

To reproduce this problem, you can run the below script that generates ONNX model from a very simple PyTorch model definition.

```python
import torch
import torch.nn.functional as F
import onnx2tf


class Model(torch.nn.Module):
    def forward(self, inputs: torch.Tensor, grid: torch.Tensor):
        return F.grid_sample(
            input=inputs,
            grid=grid,
            padding_mode="zeros",
            mode="bilinear",
            align_corners=True,
        )


model = Model()
example_inputs = torch.randn(32, 16, 36, 64)
example_grid = torch.randn(32, 36, 64, 2)
output = model.forward(example_inputs, example_grid)
print("PyTorch shape:", output.shape)

torch.onnx.export(
    Model(),
    {"inputs": example_inputs, "grid": example_grid},
    "grid_sample_reproduction.onnx",
    opset_version=16,
    input_names=["inputs", "grid"],
    output_names=["output"],
)

onnx2tf.convert(
    input_onnx_file_path="grid_sample_reproduction.onnx",
    output_folder_path="grid_sample_reproduction.tf",
    keep_shape_absolutely_input_names=["inputs", "grid"],
)
```

TFLite models are surprisingly large (18MB vs 257B in case of ONNX):

```bash
$ ls -lah grid_sample_reproduction.onnx
-rw-r--r--  1 jakubpowierza  staff   257B 26 Jul 13:45 grid_sample_reproduction.onnx

$ ls -lah grid_sample_reproduction.tf
total 73952
drwxr-xr-x   8 jakubpowierza  staff   256B 26 Jul 13:45 .
drwxr-xr-x  10 jakubpowierza  staff   320B 26 Jul 13:44 ..
drwxr-xr-x   2 jakubpowierza  staff    64B 26 Jul 13:23 assets
-rw-r--r--   1 jakubpowierza  staff    55B 26 Jul 13:45 fingerprint.pb
-rw-r--r--   1 jakubpowierza  staff    18M 26 Jul 13:45 grid_sample_reproduction_float16.tflite
-rw-r--r--   1 jakubpowierza  staff    18M 26 Jul 13:45 grid_sample_reproduction_float32.tflite
-rw-r--r--   1 jakubpowierza  staff    71K 26 Jul 13:45 saved_model.pb
drwxr-xr-x   4 jakubpowierza  staff   128B 26 Jul 13:45 variables
```

**ONNX graph visualisation:**

![grid_sample_reproduction onnx](https://github.com/PINTO0309/onnx2tf/assets/6514553/aeab4f05-1c4a-4522-8012-b1356aa4a1ce)

**TFLite graph visualisation:**

![grid_sample_reproduction_float32 tflite](https://github.com/PINTO0309/onnx2tf/assets/6514553/eb00dc4f-8555-4365-b227-fe999c52fc93)

**Comment by PINTO0309** [comment]
Unfortunately, TensorFlow does not have an OP to perform the same operations as ONNX or PyTorch. Therefore, the implementation dares to decompose only to primitive OPs.

If you have ideas for work-around implementation, please suggest them. I would love to know. I have considered it for dozens of hours and have come up with no other way than this.

By the way, I never want to use `While - Loop`. 

If in fact inference performance deteriorates significantly, it may be worth considering. If it simply increases the structure of the model, I don't see much point in discussing it.

**Comment by jpowie01** [comment]
At this moment it's not necessarily about the model performance but mostly about it's size. I don't understand why the final model weights so much (18 MB) when in fact it shouldn't contain any weights inside. All of the operations in the graph are stateless or keep relatively small constant values. I haven't found any operation in the graph that could hold those 18 MB.

As for the performance, I've just tested it quickly on my machine. The TFLite version of this model is noticeably slower than ONNX version through ONNX Runtime. I guess it's expected as this op is natively supported in ONNX Runtime that was heavily optimised throughout the past few years.

Avg latency for batch size 1 (model size = 591 KB):
- TFLite: 0.006274s
- ONNX: 0.000243s

Avg latency for batch size 32 (model size = 18 MB):
- TFLite: 0.200270s
- ONNX: 0.006721s

Avg latency for batch size 128 (model size = 72 MB):
- TFLite: 1.322181s
- ONNX: 0.025747s

The main problem here is that I want to deploy it on mobile devices, where performance and model size are very important. It seems that the only option for me now is to implement this operation as a custom layer in TensorFlow. Am I right? Are there any other solutions to this problem?

(Very primitive) extension to the reproduction script that I used to measure the timings:

```python
import timeit

import onnxruntime as ort
import tensorflow as tf

interpreter = tf.lite.Interpreter(
    model_path="grid_sample_reproduction.tf/grid_sample_reproduction_float32.tflite"
)
interpreter.allocate_tensors()
interpreter.set_tensor(0, tf.convert_to_tensor(example_inputs.detach().cpu().numpy()))
interpreter.set_tensor(1, tf.convert_to_tensor(example_grid.detach().cpu().numpy()))
avg_tflite_timing = timeit.timeit(lambda: interpreter.invoke(), number=10) / 10.0
print(f"TFLite: {avg_tflite_timing:.6f}s")

input_data = {
    "inputs": example_inputs.detach().cpu().numpy(),
    "grid": example_grid.detach().cpu().numpy()
}
ort_session = ort.InferenceSession("grid_sample_reproduction.onnx")
avg_onnx_timing = timeit.timeit(lambda: ort_session.run(None, input_data), number=10) / 10.0
print(f"ONNX: {avg_onnx_timing:.6f}s")
```

I'll try to measure it once again on mobile devices through the TFLite Benchmarking App.

**Comment by PINTO0309** [comment]
Thank you!

I would like to wait for someone to give me a pull request. 😅
I rarely get pull requests, though.

**Comment by babiking** [comment]
![image](https://github.com/PINTO0309/onnx2tf/assets/33562173/d064e654-70e0-42d0-bd71-85e288fffd9a)

I tried to reduce the GridSample intermediate ops by "broadcast" attribute and batched tf.gather_nd. It turned out a much smaller tflite model size and a faster inference process.

my implementation: https://github.com/babiking/onnx2tf/blob/a62d4325c86a2f02ece39ac6cc99b0a1920b55d4/onnx2tf/ops/GridSample.py#L165

**Comment by PINTO0309** [comment]
@babiking Thanks for the suggestion! I'm very happy. :+1: 

The reason why I am writing `GridSample` with unnecessarily verbose code is because it often expected non-Image input.   In past issues I have been told that I get conversion errors with GridSample where either H or W is 1. For many people, this was very troubling because GridSample did not seem to be aware of the need to input Image data.

If you have a generic implementation that can meet this requirement, please issue a pull request.

**Comment by PINTO0309** [comment]
@babiking 
Wonderful. It's perfect. 

If it is not too much trouble for you I am waiting for a pull request. If you are not so interested in pull requests, I will borrow the source code and merge it.

**Comment by PINTO0309** [comment]
@jpowie01 The speed is approximately 2.5 times faster.

**Comment by PINTO0309** [comment]
My PC.
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/a5a123d1-267d-4111-9e84-4c383d87a324)

**Comment by jpowie01** [comment]
That's awesome! Thank you @PINTO0309 & @babiking, you're amazing! 🙌 

I'll test the performance on my test devices once I have access to them (and once I find 5-10 minutes to run them). However, this already looks like a great improvement 😄

**Comment by jpowie01** [comment]
I've finally found some time to run the new version of onnx2tf against these models and run them on my test devices. I'm happy to say that there is a huge improvement in performance on both iPhone 14 Pro and Samsung S23 Ultra!

Avg latency for batch size 1:
- iPhone 14 Pro: 0.343 ms (before: 2.37 ms)
- Samsung S23 Ultra: 0.280 ms (before: 2.28 ms)

Avg latency for batch size 32:
- iPhone 14 Pro: 10.939 ms (before: 86.05 ms)
- Samsung S23 Ultra: 10.784 ms (before: 99.56 ms)

Avg latency for batch size 128:
- iPhone 14 Pro: 47.400 ms (before: 392.19 ms)
- Samsung S23 Ultra: 48.746 ms (before: 482.86 ms)

Thank you both for your hard work here, I really appreciate it! 🙏

**Comment by PINTO0309** [comment]
Oh, it looks like performance has improved remarkably.

It seems to have worked, so I will close this discussion. If you need to discuss anything else, please open another issue.
