### ISSUE TITLE
Transpose layer insertion in YOLO V8 models when converted to TFLite using onnx2tf when the dimensions H, W and C match

### ISSUE THREAD

**Issue by franklin-degirum** [PINTO0309/onnx2tf#454]
### Issue Type

Documentation Feature Request, Others

### OS

Linux

### onnx2tf version number

1.9.19

### onnx version number

1.14.0

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.10

### tensorflow version number

2.12.0

### Download URL for ONNX

**ONNX files**
[1x128x64x64.onnx](https://drive.google.com/file/d/1PiZCp4i9nNRn4J5YQ6Dxl4YeFIRUOS7d/view?usp=sharing)
[1x128x80x80.onnx ](https://drive.google.com/file/d/1IR4MAapAX4lkSjMtkobQvlN52SdmHn4S/view?usp=sharing) 

**Above ONNX files when converted to TFLITE using onnx2tf**
[1x64x64x128.tflite](https://drive.google.com/file/d/13bNumEbBcxOp62_w1uI5a9ub_1FIaoM_/view?usp=sharing) 
[1x80x80x128.tflite](https://drive.google.com/file/d/1h7LMf7qrOoVkv_9dcj01bunfPptNtiq2/view?usp=sharing) 

**Visual Comparison**
[1x64x64x128_tflite_after_conversion.png](https://drive.google.com/file/d/12qVp9FYrURat2iX10F9pZhBwQk4RY6T5/view?usp=sharing) 
[1x80x80x128_tflite_after_conversion.png](https://drive.google.com/file/d/1Zr5sKzm03ocxN6grDNXqI2xiqVws_Ggr/view?usp=sharing)

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Resize_0",
      "param_target": "inputs",
      "param_name": "Concat_0",
      "values": [48,48]
    },
    {
      "op_name": "Resize_1",
      "param_target": "inputs",
      "param_name": "Concat_1",
      "values": [48,48]
    },
    {
      "op_name": "Resize_2",
      "param_target": "inputs",
      "param_name": "Concat_2",
      "values": [48,48]
    },
    {
      "op_name": "Resize_3",
      "param_target": "inputs",
      "param_name": "Concat_3",
      "values": [24,24]
    },
    {
      "op_name": "Resize_4",
      "param_target": "inputs",
      "param_name": "Concat_4",
      "values": [48,48]
    },
    {
      "op_name": "Resize_5",
      "param_target": "inputs",
      "param_name": "Concat_5",
      "values": [48,48]
    },
    {
      "op_name": "Resize_6",
      "param_target": "inputs",
      "param_name": "Concat_6",
      "values": [48,48]
    },
    {
      "op_name": "Resize_7",
      "param_target": "inputs",
      "param_name": "Concat_7",
      "values": [24,24]
    },
    {
      "op_name": "Resize_8",
      "param_target": "inputs",
      "param_name": "Concat_8",
      "values": [24,24]
    },
    {
      "op_name": "Resize_9",
      "param_target": "inputs",
      "param_name": "Concat_9",
      "values": [12,12]
    },
    {
      "op_name": "Resize_10",
      "param_target": "inputs",
      "param_name": "Concat_10",
      "values": [48,48]
    },
    {
      "op_name": "Resize_11",
      "param_target": "inputs",
      "param_name": "Concat_11",
      "values": [48,48]
    },
    {
      "op_name": "Resize_12",
      "param_target": "inputs",
      "param_name": "Concat_12",
      "values": [48,48]
    },
    {
      "op_name": "Resize_13",
      "param_target": "inputs",
      "param_name": "Concat_14",
      "values": [192,192]
    },
    {
      "op_name": "Reshape_0",
      "param_target": "outputs",
      "param_name": "Reshape_0",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Reshape_1",
      "param_target": "outputs",
      "param_name": "Reshape_1",
      "post_process_transpose_perm": [0,2,3,1]
    },
    {
      "op_name": "Transpose_0",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    },
    {
      "op_name": "Transpose_1",
      "param_target": "attributes",
      "param_name": "perm",
      "values": [0,1,2,3]
    },
    {
      "op_name": "Softmax_0",
      "param_target": "attributes",
      "param_name": "axis",
      "values": 3
    }
  ]
}
```

### Description

**Purpose**: Product development

Impact: Solving this problem is crucial for the successful conversion of YOLO V8 models to TFLite using the onnx2tf tool. It will significantly impact our efforts by ensuring accurate and consistent model conversion, which is essential for the deployment of efficient object detection models on resource-constrained devices.

**Current Behavior**:

When converting a YOLO V8 model with dimensions 512x512 from ONNX format to TFLite using the onnx2tf CLI tool, unexpected Transpose layers are introduced into the resulting TFLite model. This behavior occurs specifically when the dimensions C (number of channels), H (height), and W (width) match and are the same in the residual blocks.

**Reproduction Steps**:

To reproduce the situation, follow these steps:

1. Use the onnx2tf command-line tool to convert a YOLO V8 model with dimensions 512x512 from ONNX format to TFLite.
2. Observe the TFLite model architecture and layers introduced during the conversion process.

Attached are two TFLite model files: "1x64x64x128.tflite" and "1x80x80x128.tflite." along with their netron view. These files serve as small examples to demonstrate the issue. The "1x64x64x128.tflite" model showcases the introduction of Transpose layers when the dimensions C, H, and W match, while the "1x80x80x128.tflite" model does not exhibit this behavior. These examples emphasize that the problem is specifically related to cases where C, H, and W values are equal.

**Comment by PINTO0309** [comment]
The version of onnx2tf is too old. Please update it regularly. It is now v1.15.12.

```
onnx2tf -i 1x128x64x64.onnx -cotof
```

[1x128x64x64_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/12353821/1x128x64x64_float32.tflite.zip)

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/77af550a-d100-46b9-b946-500fcb50abad)

**Comment by franklin-degirum** [comment]
Quick update – your suggestion to update onnx2tf to v1.15.12 and onnxsim to v0.4.33 did the trick! Thanks for the help

**Comment by PINTO0309** [comment]
In addition, there are few patterns now that require changing the behavior of onnx2tf using JSON.

**Comment by ChenLiangChong** [comment]
@franklin-degirum 
I'm working on the same transpose issue. Is there any suggestion for me to adjustment my json file
https://github.com/PINTO0309/onnx2tf/issues/550
