### ISSUE TITLE
Error while converting Retinaface onnx model to tensorflow

### ISSUE THREAD

**Issue by Mudasar-Makandar** [PINTO0309/onnx2tf#458]
### Issue Type

Others

### OS

OSX

### onnx2tf version number

1.15.10

### onnx version number

1.13.1

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

det_10g.onnx file located inside buffalo_l.zip file at [insightface-releases](https://github.com/deepinsight/insightface/releases/tag/v0.7)

### Parameter Replacement JSON

```json
I don't know which parameters to be replaced. Help needed :(
```

### Description

1. Personal Development.
2. I have converted w600k_r50.onnx(face-recognition model) to TFLite model but facing issue to convert det_10g.onnx(face-detection model)
3. Error logs:
4. 
ERROR: input_onnx_file_path: models/trained_models/det_10g.onnx
ERROR: onnx_op_name: MaxPool_9
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

**Comment by PINTO0309** [comment]
```bash
onnx2tf -i w600k_r50.onnx -cotof -b 1
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/62216dac-9000-4bf1-9a2e-c7c17f896579)
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/2f3c6cf0-f757-4181-8eb5-bcf121987fe1)

**Comment by PINTO0309** [comment]
This ONNX file has a broken definition of final output.
```
onnxsim det_10g.onnx det_10g.onnx --overwrite-input-shape input.1:1,3,640,640

onnx2tf -i det_10g.onnx -cotof
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/f576c14f-67f7-4903-8f4b-94c24189fd03)
