### ISSUE TITLE
Reshape Unmatched max abs error when doing ONNX and TF output value validation

### ISSUE THREAD

**Issue by jlamperez** [PINTO0309/onnx2tf#478]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.16.2

### onnx version number

1.14.1

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

[subgraph_model.zip](https://github.com/PINTO0309/onnx2tf/files/12514688/subgraph_model.zip)

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Personal
2. What 

```
$ onnx2tf -i subgraph_model.onnx -cotof -cotoa 1e-4

ONNX and TF output value validation started =========================================
INFO: validation_conditions: np.allclose(onnx_outputs, tf_outputs, rtol=0.0, atol=0.0001, equal_nan=True)
INFO: onnx_output_name: 556 tf_output_name: tf.nn.relu/Relu:0 shape: (1, 64, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 557 tf_output_name: tf.math.add/Add:0 shape: (1, 2, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 558 tf_output_name: tf.math.add_1/Add:0 shape: (1, 8, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 560 tf_output_name: tf.math.add_2/Add:0 shape: (1, 20, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 559 tf_output_name: tf.math.multiply_1/Mul:0 shape: (1, 8, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 564 tf_output_name: tf.compat.v1.transpose/transpose:0 shape: (1, 20, 20, 2) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 581 tf_output_name: tf.compat.v1.transpose_1/transpose:0 shape: (1, 20, 20, 20) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 573 tf_output_name: tf.compat.v1.transpose_2/transpose:0 shape: (1, 20, 20, 8) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: 571 tf_output_name: tf.reshape/Reshape:0 shape: (1, 800, 1) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: kps_32 tf_output_name: tf.reshape_1/Reshape:0 shape: (1, 800, 10) dtype: float32 validate_result:  Unmatched  max_abs_error: 13.271623611450195
INFO: onnx_output_name: bbox_32 tf_output_name: tf.reshape_2/Reshape:0 shape: (1, 800, 4) dtype: float32 validate_result:  Matches 
INFO: onnx_output_name: score_32 tf_output_name: tf.math.sigmoid/Sigmoid:0 shape: (1, 800, 1) dtype: float32 validate_result:  Matches 
```
![subgraph_model](https://github.com/PINTO0309/onnx2tf/assets/8319840/6b479aee-4fe5-4185-9027-4eafd596c01e)

I don't understand why `kps_32` ONNX output name is giving this huge error when converting to TF. For me, the 3 branches in the model are similar. The only weird thing that I see is that the `kps_32` branch has an input size of 1x20x20x20 before the Reshape and since the last three numbers are the same, it is causing problems.

Thank you,

Regards.

**Comment by PINTO0309** [comment]
The tool has many features that automatically estimate the correct position of the axes, but after `Reshape` and `Transpose` it often gets confused. Automatic error correction does not work well, especially when most axes have values of the same magnitude. This is also stated in the REAME and has often been explained the same way in past issues.

`1x20x20x20` is difficult to determine whether it is an NCHW or an NHWC, because it is difficult to determine whether it is an NCHW or an NHWC.

If it is clear that the tool's automatic estimation of axes will not work, a human can instruct the tool to perform a correction action to correctly correct the conversion results.

https://github.com/PINTO0309/onnx2tf#parameter-replacement

- replace.json
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "Reshape_255",
        "param_target": "inputs",
        "param_name": "581",
        "pre_process_transpose_perm": [0,2,3,1]
      }
    ]
  }
  ```

```bash
onnx2tf -i subgraph_model.onnx -cotof -prf replace.json
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/5a0cda10-ccf8-4f3e-831f-f97a0bdc39fc)

**Comment by jlamperez** [comment]
Hi @PINTO0309,

Thank you very much for the help and your time answering this question in detail. This tool is very cool.

**Comment by PINTO0309** [comment]
Try it.

Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.16.8

**Comment by jlamperez** [comment]
> Try it. JSON is not required.
> 
> Fixes: https://github.com/PINTO0309/onnx2tf/releases/tag/1.16.8

Yes, it works for me. Thank you very much!
