### ISSUE TITLE
Bug in TFlite NonMaxSuppression

### ISSUE THREAD

**Issue by Hyunseok-Kim0** [PINTO0309/onnx2tf#48]
### Issue Type

Others

### onnx2tf version number

1.2.9

### Download URL for ONNX

Any onnx file with NonMaxSuppression can be used. Please use code below for simple debugging.

```python
import os
import shutil

import onnxruntime
import tensorflow as tf
import torch
import torchvision
from torch import nn

from onnx2tf import convert


class dummy_network(nn.Module):

    def __init__(self):
        super(dummy_network, self).__init__()

    def forward(self, boxes, scores):
        # unique with sort
        result = torchvision.ops.nms(boxes, scores, iou_threshold=0.3)

        return result


def main():
    os.makedirs("tflite", exist_ok=True)
    model = dummy_network()
    model.eval()

    dummy_name = "dummy_nms"
    onnx_save_path = f"tflite/{dummy_name}.onnx"
    temp_tflite = "tflite/model_float32.tflite"
    tflite_save_path = f"tflite/{dummy_name}.tflite"

    dummy_input_boxes = torch.abs(torch.randn(32, 4, dtype=torch.float32))
    dummy_input_boxes = torch.concat([dummy_input_boxes, dummy_input_boxes], dim=0)
    dummy_scores = torch.abs(torch.randn(32, dtype=torch.float32))
    dummy_scores = torch.concat([dummy_scores, dummy_scores], dim=0)

    torch.onnx.export(model,
                      args=(dummy_input_boxes, dummy_scores),
                      f=onnx_save_path,
                      input_names=["boxes", "scores"],
                      output_names=["nms_result"],
                      opset_version=11)

    # get onnx output
    # -----------------------------------------------------------------------------------------------
    onnx_session = onnxruntime.InferenceSession(onnx_save_path, providers=['CPUExecutionProvider'])
    onnx_inputs = dict(boxes=dummy_input_boxes.numpy(), scores=dummy_scores.numpy())
    onnx_outputs = onnx_session.run(None, onnx_inputs)

    convert(onnx_save_path, output_folder_path="tflite")
    shutil.move(temp_tflite, tflite_save_path)

    # # compare torch output and onnx output
    # np.testing.assert_allclose(onnx_output, torch_output.numpy())
    #
    # get tflite output
    # -----------------------------------------------------------------------------------------------
    tflite_onnx2tf = tf.lite.Interpreter(model_path=tflite_save_path)
    tflite_onnx2tf.allocate_tensors()
    tflite_onnx2tf.set_tensor(tflite_onnx2tf.get_input_details()[0]['index'], dummy_input_boxes.numpy())
    tflite_onnx2tf.set_tensor(tflite_onnx2tf.get_input_details()[1]['index'], dummy_scores.numpy())
    tflite_onnx2tf.invoke()
    tflite_output = [tflite_onnx2tf.get_tensor(i['index']) for i in tflite_onnx2tf.get_output_details()][0]

    print("convert done")

    return


if __name__ == "__main__":
    main()

```

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Personal development

2. What: onnx NonMaxSuppression operator is converted using `tf.image.non_max_suppression`. However, it looks there is bug in tensorflow operation. 
https://github.com/tensorflow/tensorflow/issues/51629
For now, `tf.image.non_max_suppression` always pad the number of output to `max_output_boxes_per_class`. The result below shows the difference between onnx and tflite output.
![Screenshot from 2022-12-15 15-02-08](https://user-images.githubusercontent.com/34959032/207784625-292d6401-88d1-41ec-b25d-2ab5d455f0d4.png)
There is another operation, `tf.image.non_max_suppression_padded` which using extra parameter `pad_to_max_output_size`. I thought this problem can be solved by setting `pad_to_max_output_size` to False, but it also didn't work.
![Screenshot from 2022-12-15 15-01-28](https://user-images.githubusercontent.com/34959032/207785277-55768d2e-2cd4-4626-8d8b-d32d3a94bacf.png)
Returned indices are not correct, looks like the implementation is totally different between `tf.image.non_max_suppression_padded` and `tf.image.non_max_suppression`.

3. How: This problem can be solved by adding single line of code `selected_indices = tf.unique(selected_indices).y` after line number 208. However, sometimes last element of indices can be wrong value since this solution is just removing duplicated indices.
https://github.com/PINTO0309/onnx2tf/blob/db8c72220f9ce9a783089c89eff0b54c0f572141/onnx2tf/ops/NonMaxSuppression.py#L202-L208

**Comment by PINTO0309** [comment]
I realize this is a silly fix, but I could force the output to match by doing the following

```python
class NonMaxSuppressionV2(tf.keras.layers.Layer):

    def __init__(self):
        super(NonMaxSuppressionV2, self).__init__()
        self.nms_ops = tf.compat.v1.raw_ops.NonMaxSuppressionV2

    def call(self, boxes, scores, max_output_size, iou_threshold):
        return self.nms_ops(
            boxes=boxes,
            scores=scores,
            max_output_size=max_output_size,
            iou_threshold=iou_threshold,
        )

  : 
  :
            # get the selected boxes indices
            tf_nms_ops = NonMaxSuppressionV2()
            selected_indices = tf_nms_ops(
                boxes=tf_boxes,
                scores=tf_scores,
                max_output_size=max_output_boxes_per_class,
                iou_threshold=iou_threshold,
            )
```

```
onnx_outputs
array([ 0, 30, 22, 19, 20, 26,  6, 31,  2, 28, 21, 12, 27, 25,  8,  3, 18, 17,  5, 23, 11,  4, 24,  1,  7, 13], dtype=int64)

tflite_output
array([ 0, 30, 22, 19, 20, 26,  6, 31,  2, 28, 21, 12, 27, 25,  8,  3, 18, 17,  5, 23, 11,  4, 24,  1,  7, 13])
```
![image](https://user-images.githubusercontent.com/33194443/207842857-670dc603-d16d-42cb-bb71-803302563303.png)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.2.10

**Comment by PINTO0309** [comment]
I see. I hadn't thought of the idea of using decorators to compensate for behavior. Interesting. :+1:

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.2.11

**Comment by Hyunseok-Kim0** [comment]
https://github.com/PINTO0309/onnx2tf/blob/b0d6576e20f6104e6e57a6f4e34c0d67837824fd/onnx2tf/ops/NonMaxSuppression.py#L233-L242

I guess those lines of code no longer needed since we are now using `non_max_suppression_v4`, which has `score_threshold` parameter. Can you delete that part in later commit?

**Comment by PINTO0309** [comment]
OK, I will remove it immediately.

**Comment by PINTO0309** [comment]
Done.
https://github.com/PINTO0309/onnx2tf/releases/tag/1.2.12

**Comment by Hyunseok-Kim0** [comment]
Thank you, closing issue.
