### ISSUE TITLE
New `onnx2tf>=1.17.6` export bug `TypeError: You are passing KerasTensor`

### ISSUE THREAD

**Issue by glenn-jocher** [PINTO0309/onnx2tf#515]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.17.7

### onnx version number

1.14.1

### onnxruntime version number

1.16.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.13.0

### Download URL for ONNX

[yolov8n.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/12708693/yolov8n.onnx.zip)

### Parameter Replacement JSON

```json
None
```

### Description

onnx2tf exports are failing for YOLOv8 with the latest version. To reproduce:

```bash
pip install -U ultralytics

yolo export model=yolov8n.pt format=tflite
```

Link to the Ultralytics CI showing this error:
https://github.com/ultralytics/ultralytics/actions/runs/6282249524/job/17077943471?pr=5046

<img width="1999" alt="Screenshot 2023-09-24 at 16 09 46" src="https://github.com/PINTO0309/onnx2tf/assets/26833433/6b5aba29-7429-45bf-b38a-84e4407f3efe">

**Comment by glenn-jocher** [comment]
@PINTO0309 the same export works correctly with `onnx2tf==1.16.31`:

```bash
pip install -U ultralytics
pip install 'onnx2tf!=1.17.*'

yolo export model=yolov8n.pt format=tflite
```

**Comment by glenn-jocher** [comment]
@PINTO0309 1.17.5 is the last correctly working version for me. You might want to yank 1.17.6 and 1.17.7 from PyPI until you can find a fix. This will hide them from pip install commands, so that 1.17.5 will be installed by new users while you work on a fix for 1.17.8.

**Comment by PINTO0309** [comment]
ONNX you attached.

[yolov8n.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/12708693/yolov8n.onnx.zip)

https://github.com/PINTO0309/onnx2tf#environment

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/883c9eee-153e-4ae3-bb1f-80ae0f983ab5)

```bash
pip show tensorflow onnx onnxruntime-gpu ml_dtypes onnx2tf

Name: tensorflow
Version: 2.14.0rc1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: tensorflow-decision-forests, tensorflowjs
---
Name: onnx
Version: 1.14.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfaidata.foundation
License: Apache License v2.0
Requires: numpy, protobuf, typing-extensions
Required-by: insightface, onnx-graphsurgeon, onnx-tensorrt, onnxsim, tf2onnx
---
Name: onnxruntime-gpu
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by: 
---
Name: ml-dtypes
Version: 0.2.0
Summary: 
Home-page: 
Author: 
Author-email: ml_dtypes authors <ml_dtypes@google.com>
License: 
Requires: numpy, numpy
Required-by: jax, jaxlib, tensorflow
---
Name: onnx2tf
Version: 1.17.7
Summary: Self-Created Tools to convert ONNX files (NCHW) to TensorFlow/TFLite/Keras format (NHWC). The purpose of this tool is to solve the massive Transpose extrapolation problem in onnx-tensorflow (onnx-tf).
Home-page: https://github.com/PINTO0309/onnx2tf
Author: Katsuya Hyodo
Author-email: rmsdh122@yahoo.co.jp
License: MIT License
Requires: 
Required-by: simple-onnx-processing-tools
```

```
onnx2tf -i yolov8n.onnx -cotof
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/2354a79e-e65a-4d6c-9b52-9ef05e1fe2d0)

**Comment by glenn-jocher** [comment]
Ok got it, thanks!
