### ISSUE TITLE
(1)Not correctly recognize depthwise_conv (2)-oiqt could not skip SavedModel

### ISSUE THREAD

**Issue by AngLi666** [PINTO0309/onnx2tf#542]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.18.14

### onnx version number

1.14.1

### onnxruntime version number

1.16.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.14.0

### Download URL for ONNX

https://drive.google.com/file/d/1aZyXo67XzorAAsZavdVDXp_kKPQg9bP8/view?usp=sharing

### Parameter Replacement JSON

```json
I have no idea what is this
```

### Description

1. Personal development/Product prototype
2. Two issues to solve: (a) onnx2tf recognizes DepthwiseConv1d as GroupConv1d, which make it hardly converted to SavedModel (without -dgc). (b)  -oiqt option will not skip SavedModel, therefore, I could not directly obtain the int8 quantized tflite model
3. I reviewed the open/close issues on Github to address issue(a), one suggests that using -oiqt option. However, it seems -oiqt still requires SavedModel, issues(b) occurs. I step backwards and tried to address issue(a), I found onnx_tensorflow solved issue(a) (for DepthwiseConv2D). I tried onnx_tensorflow, it fail at parsing onnx model. 
4. It seems sometimes onnx2tf will incorrectly recognize Depthwise Convolution, it happed once before, I work around by re-writing network using tensorflow. I think it will be benifical to this onnx2tf tool to address this issue.
5. 
onnx2tf closed issue suggests using -oiqt option to directly obtain quantized model, to avoid GroupConv issue:
https://github.com/PINTO0309/onnx2tf/issues/360#issuecomment-1548013893

onnx_tensorflow solution for recognizing depthwise conv : 
https://github.com/onnx/onnx-tensorflow/issues/473
https://stackoverflow.com/questions/66675299/pytorch-onnx-tensorflow-tflite-generates-lots-of-redundant-conv2d-ope

<img width="1925" alt="1698896189547" src="https://github.com/PINTO0309/onnx2tf/assets/77546516/be353a59-3591-4656-a630-ee6c7c85f9ee">

**Comment by PINTO0309** [comment]
> (a) onnx2tf recognizes DepthwiseConv1d as GroupConv1d, which make it hardly converted to SavedModel (without -dgc).

It is a bug in TensorFlow's saved_model format. onnx2tf has no choice but to convert it to GroupConvolution.

> -oiqt option will not skip SavedModel, therefore, I could not directly obtain the int8 quantized tflite model

I know that I can perform int8 quantization without going through saved_model. However, I am going out on a limb and specifying it that way because there are various problems with the Keras model.

There are too many problems to explain.
