### ISSUE TITLE
Failed to convert model from segmentation_models_pytorch with dynamic shape

### ISSUE THREAD

**Issue by hgaiser** [PINTO0309/onnx2tf#543]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.18.14

### onnx version number

1.14.1

### onnxruntime version number

1.16.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.14.0

### Download URL for ONNX

I created the following model:

```py
import segmentation_models_pytorch as smp
import torch

model = smp.DeepLabV3(encoder_name='mobilenet_v2')
dummy_input = torch.randn((1, 3, 800, 512), dtype=torch.float32)
torch.onnx.export(
    model,
    (dummy_input,),
    'converted.onnx',
    export_params=True,
    input_names=['images'],
    output_names=['segmentations'],
    dynamic_axes={
        'images': {2: 'height', 3: 'width'},
        'segmentations': {2: 'height', 3: 'width'},
    },
    verbose=False
)
```

Github doesn't allow me to upload the resulting file, but [here](https://nextcloud.hgaiser.nl/s/gTpWGTXmjmPRb4H) it is in case you want to try it.

### Parameter Replacement JSON

It wasn't entirely clear if this file is always required. At the moment I haven't generated or created a parameter replacement file.

### Description

1. Research or product development.
2. See attached log.
[output.txt](https://github.com/PINTO0309/onnx2tf/files/13335755/output.txt)

3. Created the model using the script above, and ran the following command:
   ```
   docker run --rm -it \
     -v `pwd`:/workdir \
     -w /workdir \
     docker.io/pinto0309/onnx2tf:1.18.14 onnx2tf -i converted.onnx -o tflite_output -osd -coion
   ```
4. The accelerator I want to run uses tflite.
5. I found a seemingly very related issue (https://github.com/PINTO0309/onnx2tf/issues/388) but the way it was solved was not clear.

My guess is that I am misunderstanding some step in the conversion process. If you could point me into the right direction, that would be very much appreciated!

As a sidenote: thank you for your efforts in this repository, it is much appreciated! It is unfortunate that there is no "official" converter, but this is pretty close to that :).

**Comment by hgaiser** [comment]
@AlexanderLutsenko thank you! I was stuck on this for a while, at the very least this has given me new information to process. I will try your suggestion when I have time (which might take some weeks). Since tflite doesn't seem to support dynamic input shapes still, should we close this issue? It seems more of an upstream issue.

**Comment by PINTO0309** [comment]
```
docker run --rm -it \
-v `pwd`:/workdir \
-w /workdir \
docker.io/pinto0309/onnx2tf:1.20.0
```
```
onnx2tf -i converted.onnx -osd -coion
```
```
saved_model output started ==========================================================
saved_model output complete!
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1713575690.662316 2656523 tf_tfl_flatbuffer_helpers.cc:390] Ignored output_format.
W0000 00:00:1713575690.662348 2656523 tf_tfl_flatbuffer_helpers.cc:393] Ignored drop_control_dependency.
Float32 tflite output complete!
W0000 00:00:1713575724.236088 2656523 tf_tfl_flatbuffer_helpers.cc:390] Ignored output_format.
W0000 00:00:1713575724.236105 2656523 tf_tfl_flatbuffer_helpers.cc:393] Ignored drop_control_dependency.
Float16 tflite output complete!
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/eb0cb6dc-c1ea-4646-8a1c-a4da935e7298)
