### ISSUE TITLE
I convert onnx to tensorflow use -osd option, saved_model  wierd,  almost every layer have many output

### ISSUE THREAD

**Issue by allenliuvip** [PINTO0309/onnx2tf#549]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.18.14

### onnx version number

1.15.0

### onnxruntime version number

1.16.3

### onnxsim (onnx_simplifier) version number

0.4.35

### tensorflow version number

2.15.0

### Download URL for ONNX

链接: https://pan.baidu.com/s/1Vxs1PniBLd6oBV0D9d0a8A?pwd=91sy 提取码: 91sy

### Parameter Replacement JSON

```json
onnx2tf -i 4_0_0_80x80_MiniFASNetV1SE.pthmini.onnx -ois input-1:1,3,80,80 -osd
```

### Description

1 Personal development 
2 onnx->-osd ,  all log is normal , no error log
3 just anaylise the code
4
5 just download from github

**Comment by PINTO0309** [comment]
Baidu is difficult to access from outside China. Please use another drive to share ONNX.
