### ISSUE TITLE
[ssdlite320_mobilenet_v3_large] Wrong shapes during inference

### ISSUE THREAD

**Issue by zeyadkay** [PINTO0309/onnx2tf#551]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.18.14

### onnx version number

1.14.1

### onnxruntime version number

1.16.0

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.14.0

### Download URL for ONNX

[model.zip](https://github.com/PINTO0309/onnx2tf/files/13539550/model_orig.zip)

### Parameter Replacement JSON

```json
{}
```

### Description

1. I am trying to convert ```ssdlite320_mobilenet_v3_large``` model from torchvision to tflite.
2. Model conversion is successful but when doing inference it crashes due to incompatible shapes at a specific ```Add``` Node. Here is the log (https://logpaste.com/nVY6CYjW)
3. When looking at the graph after conversion, the output shapes are correct but during inference the output from the ```Gather``` node is ```[300, 4]``` while the ```Reshape``` has ```[299,1]```. I think the problem is with the ```Reshape``` pathway because when interrupting model conversion at ```Gather``` I get the expected shape but at the other pathway I could not even interrupt model conversion.
![edited](https://github.com/PINTO0309/onnx2tf/assets/149577462/312c5e11-9cf9-41bc-ac7f-32bd31c9a4ea)

**Comment by VuHuy-cse-9** [comment]
I had the same a issue on MobileNetv3. I used onnx2tf == 1.19.11.

**Comment by PINTO0309** [comment]
Remove all redundant post-processing, including NonZero. Shape estimation is not possible.
