### ISSUE TITLE
module 'tensorflow' has no attribute 'random' for tensorflow 2.15, but 2.14.0 does

### ISSUE THREAD

**Issue by mprynce** [PINTO0309/onnx2tf#556]
### Issue Type

Others

### OS

OSX

### onnx2tf version number

1.19.0

### onnx version number

1.15.0

### onnxruntime version number

1.16.3

### onnxsim (onnx_simplifier) version number

0.4.35

### tensorflow version number

2.15.0

### Download URL for ONNX

file:// local SAM

### Parameter Replacement JSON

```json
{}
```

### Description

1. Product development
2.  % onnx2tf -i ../../../models/sam/onnx/sam_vit_b_01ec64.decoder.onnx
Traceback (most recent call last):
  File "/Users/mike/miniconda3/envs/whatstyle-dev/bin/onnx2tf", line 5, in <module>
    from onnx2tf import main
  File "/Users/mike/miniconda3/envs/whatstyle-dev/lib/python3.11/site-packages/onnx2tf/__init__.py", line 1, in <module>
    from onnx2tf.onnx2tf import convert, main
  File "/Users/mike/miniconda3/envs/whatstyle-dev/lib/python3.11/site-packages/onnx2tf/onnx2tf.py", line 26, in <module>
    tf.random.set_seed(0)
    ^^^^^^^^^
AttributeError: module 'tensorflow' has no attribute 'random'
3. Tested the call wioth tensorflow 2.14.0 and the random does exist
4. To export onnx to TFJS
5. None

**Comment by PINTO0309** [comment]
It must be a bug in the TensorFlow binary for mac.
```
$ $ uname -a
Linux ubuntu2004 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 22.04.3 LTS \n \l

$ pip show tensorflow

Name: tensorflow
Version: 2.15.0.post1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/b920405/.local/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: tensorflow-decision-forests, tensorflowjs

$ python
>>> import tensorflow as tf
>>> tf.random.set_seed(0)
>>> 
```

**Comment by mprynce** [comment]
Thank you for the quick response!
