### ISSUE TITLE
ValueError in MaxPool Layer during ONNX to TensorFlow Conversion with 3D Input

### ISSUE THREAD

**Issue by TsuneariKuroiwa** [PINTO0309/onnx2tf#579]
### Issue Type

Others

### OS

OSX

### onnx2tf version number

1.19.7

### onnx version number

1.15.0

### onnxruntime version number

1.16.3

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.15.0

### Download URL for ONNX

https://drive.google.com/file/d/1r4sN4vPmPa_oDTmV_qEVTOQSPXuPhBZO/view?usp=sharing

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
      {
        "op_name": "/Transpose",
        "param_target": "attributes",
        "param_name": "perm",
        "values": [0,2,3,1]
      }
    ]
  }
```

### Description

Purpose: Research development

The conversion is executed using the command `onnx2tf -i UM_best_model.onnx' -prf param_replacement.json`.

The ONNX model is expected to have a 3-dimensional input to the MaxPool layer, but the error indicates a requirement for a 4-dimensional input.

```
The error message and relevant information are as follows:
`INFO: 7 / 26
INFO: onnx_op_type: MaxPool onnx_op_name: /pool1/MaxPool
INFO:  input_name.1: /Squeeze_output_0 shape: [1, 32, 51] dtype: float32
INFO:  output_name.1: /pool1/MaxPool_output_0 shape: [1, 32, 25] dtype: float32
INFO:  output_name.2: /pool1/MaxPool_output_1 shape: [1, 32, 25] dtype: int64
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 310, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 383, in inverted_operation_enable_disable_wrapper_func
    result = func(*args, **kwargs)
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 53, in get_replacement_parameter_wrapper_func
    func(*args, **kwargs)
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/onnx2tf/ops/MaxPool.py", line 334, in make_node
    tf.nn.max_pool_with_argmax(
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/keras/src/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/Users/blackrock/anaconda3/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.nn.max_pool_with_argmax" (type TFOpLambda).

Shape must be rank 4 but is rank 3 for '{{node tf.nn.max_pool_with_argmax/MaxPoolWithArgmax}} = MaxPoolWithArgmax[T=DT_FLOAT, Targmax=DT_INT64, include_batch_in_index=true, ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1]](Placeholder)' with input shapes: [1,51,32].

Call arguments received by layer "tf.nn.max_pool_with_argmax" (type TFOpLambda):
  • input=tf.Tensor(shape=(1, 51, 32), dtype=float32)
  • ksize=['2']
  • strides=['2']
  • padding='VALID'
  • data_format=NHWC
  • output_dtype=tf.int64
  • include_batch_in_index=True
  • name=None`
```

The input to the MaxPool layer is inherently 3-dimensional, as expected in my model's architecture. However, during the conversion process, the tf.nn.max_pool_with_argmax layer seems to require a 4-dimensional input. I am unsure how to address this discrepancy.

Could you please provide guidance or suggestions on how to resolve this issue? Any insights or recommendations to ensure the correct handling of the 3-dimensional input during the ONNX to TensorFlow conversion would be greatly appreciated.

Thank you in advance for your assistance and time.

**Comment by PINTO0309** [comment]
It's the same issue as the following issue. TensorFlow's `max_pool_with_argmax` does not support 3D. Therefore, I need to force myself to modify onnx2tf and upgrade it to support 3D tensor input. Wait a bit.

[[MMVC]Error occurs stating 'Resize operations other than 4D and 5D are not supported' for a 3D operation #283](https://github.com/PINTO0309/onnx2tf/issues/283)

**Comment by PINTO0309** [comment]
That said, there are things you can do yourself without having to implement special workarounds in onnx2tf. Just Reshape to 4D before MaxPool and squeeze to 3D again after Pooling.

**Comment by PINTO0309** [comment]
See: https://github.com/PINTO0309/onnx2tf/pull/580

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/817898fe-f1c0-43c0-9ded-7f159acde00f)

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf/releases/tag/1.19.11

**Comment by TsuneariKuroiwa** [comment]
Thank you for your help! I am now able to convert the model.
