### ISSUE TITLE
How to convert onnx(NCHW) to NHWC and write back to onnx file ????  Because my HW takes onnx file as input in NHWC format  

### ISSUE THREAD

**Issue by abhishek27m1992github** [PINTO0309/onnx2tf#584]
### Issue Type

Others

### OS

Others

### onnx2tf version number

na

### onnx version number

na

### onnxruntime version number

na

### onnxsim (onnx_simplifier) version number

na

### tensorflow version number

na

### Download URL for ONNX

na

### Parameter Replacement JSON

```json
na
```

### Description

it's just a question or may be a feature request.

**Comment by abhishek27m1992github** [comment]
My H/W can take .tflite file as input( which is already in NWHC format) and works file. but to use variety of models genarted from different framework we are now fixing  onnx as common input so it can take  .onnx file as input but should be in NHWC format. 
so came across your solution but i think it converts onnx2tflite .

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/simple-onnx-processing-tools

**Comment by abhishek27m1992github** [comment]
> https://github.com/PINTO0309/simple-onnx-processing-tools

scc4onnx:  as shown in example it adds transpose as extra layer in order to convert to NHWC but it brings extra overhead to H/W performance. i want the output without transpose layer similar like onnx2tf tool. So the other way is to change/reshuffle the weight  matrix.  Can your onnx2tf tool write the data into onnx in NHWC format  or any tool without adding transpose layer ?
