### ISSUE TITLE
How to convert onnx(NCHW) to NHWC(without adding transpose) and write back to onnx file ????

### ISSUE THREAD

**Issue by abhishek27m1992github** [PINTO0309/onnx2tf#586]
### Issue Type

Feature Request

### OS

Windows

### onnx2tf version number

na

### onnx version number

na

### onnxruntime version number

na

### onnxsim (onnx_simplifier) version number

na

### tensorflow version number

na

### Download URL for ONNX

na

### Parameter Replacement JSON

```json
na
```

### Description

We already developed out NN Accelerator which takes input .tflite & .onnx files in NHWC format.

https://github.com/PINTO0309/simple-onnx-processing-tools

As per tools mentioned in above link, we tried scc4onnx.
scc4onnx: as shown in example it adds transpose as an extra layer in order to convert to NHWC but it brings extra overhead to H/W performance. i want the output without transpose layer similar like onnx2tf tool which converts into NHWC format. Can your onnx2tf tool write the data into onnx file in NHWC format or any tool which to solve the massive Transpose extrapolation problem. I think you can add this feature either in onnx2tf or scc4onnx which should convert NCHW(onnx) to NHWC(onnx).  It will be a great help to us and many others which are currently facing this biggest issue.

https://github.com/ZhangGe6/onnx-modifier:   here we have to manually edit for each node so use case is totally different.  

Thanks for your help.

**Comment by PINTO0309** [comment]
I don't know what you expect me to do. ONNX works only in `NCHW` format.  It is impossible in principle.

If you can't tolerate only one `Traspose`, give up. I cannot change the ONNX specifications.

**Comment by PINTO0309** [comment]
```
onnx2tf -i aaa.onnx -kat {input_op_name}
```

**Comment by abhishek27m1992github** [comment]
> I don't know what you expect me to do. ONNX works only in `NCHW` format. It is impossible in principle.
> 
> If you can't tolerate only one `Transpose`, give up. I cannot change the ONNX specifications.

So sorry if i'm unable to make you understand. I will try my best to explain.

First i'm not using onnxruntime. we have our own runtime SDK & NN hardware which accepts NHWC format.

if i convert pytorch models to tflite via onnx ---> so many transpose layer gets added.  so I used your tool openvino2tflite which nicely removes transpose layers.  

Now i want to add support .onnx to my SDK. My assumption is if we somehow  only change memory format to NHWC - aka how tensor laid in memory i.e. weights & biases etc...    in onnx file then i feed  same .onnx to my SDK & H/W it should work.  but i know it will not work in onnx runtime.  Please correct me if i'm wrong.   

So that's what i wanted to do with your tool.
