### ISSUE TITLE
Please do reply for the last time either this issue or  @ How to convert onnx(NCHW) to NHWC(without adding transpose) and write back to onnx file #586

### ISSUE THREAD

**Issue by abhishek27m1992github** [PINTO0309/onnx2tf#587]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

na

### onnx version number

na

### onnxruntime version number

na

### onnxsim (onnx_simplifier) version number

na

### tensorflow version number

na

### Download URL for ONNX

na

### Parameter Replacement JSON

```json
na
```

### Description

> I don't know what you expect me to do. ONNX works only in `NCHW` format. It is impossible in principle.
> 
> If you can't tolerate only one `Transpose`, give up. I cannot change the ONNX specifications.

So sorry if i'm unable to make you understand. I will try my best to explain.

First i'm not using onnxruntime. we have our own runtime SDK & NN hardware which accepts NHWC format.

if i convert pytorch models to tflite via onnx ---> so many transpose layer gets added.  so I used your tool openvino2tflite which nicely removes transpose layers.  

Now i want to add support .onnx to my SDK. My assumption is if we somehow  only change memory format to NHWC  - aka how tensor laid in memory i.e. weights & biases etc...    in onnx file then i feed  same .onnx to my SDK & H/W it should work.  but i know it will not work in onnx runtime.  Please correct me if i'm wrong.   

So that's what i wanted to do with your tool.

**Comment by PINTO0309** [comment]
>if i convert pytorch models to tflite via onnx ---> so many transpose layer gets added. so I used your tool openvino2tflite which nicely removes transpose layers.

First, this repository is onnx2tf. `onnx to tf`. Not onnx-tensorflow. In the first place, I would have defined a requirement that when you submit an issue to this repository, you must always attach a sample ONNX file. Why do you ignore it? Also, questions outside of the conversion flow intended by this repository do not make sense.

>Now i want to add support .onnx to my SDK. My assumption is if we somehow only change memory format to NHWC - aka how tensor laid in memory i.e. weights & biases etc... in onnx file then i feed same .onnx to my SDK & H/W it should work. but i know it will not work in onnx runtime. Please correct me if i'm wrong.

No. You are completely wrong. onnxruntime expects the NCHW tensor. Therefore, the idea of a memory map is irrelevant. Discussion of ONNX model execution is outside the scope of this repository and should be discussed in the onnxruntime or onnx repositories.

I'm not a handyman.
