### ISSUE TITLE
Depth_Anything to ONNX model's conversion failed

### ISSUE THREAD

**Issue by Meleko96** [PINTO0309/onnx2tf#589]
### Issue Type

Documentation Feature Request

### OS

Linux

### onnx2tf version number

1.19.11

### onnx version number

1.15.0

### onnxruntime version number

1.17.0

### onnxsim (onnx_simplifier) version number

0.4.35

### tensorflow version number

2.12.1

### Download URL for ONNX

https://s3.ap-northeast-2.wasabisys.com/pinto-model-zoo/439_Depth-Anything/resources_s.tar.gz

### Parameter Replacement JSON

```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "wa/depth_head/refinenet4/Resize",
      "param_target": "inputs",
      "param_name": "wa/Constant_5_output_0",
      "values": [34,45]
    }
  ]
}
```

### Description

Hello,
I am trying to convert the depth_anything onnx model to **tensorflow lite**. The model's variant is depth_anything_vits14_1x3x480x640.onnx.
The command that I used is: 
`onnx2tf -i depth_anything_vit_480x640.onnx -b 1 -osd -oiqt -ioqd int8 -coion -prf replace_param_depth_any.json` 
I got the following error. 
![image](https://github.com/PINTO0309/onnx2tf/assets/64444088/ba7c36d7-5f61-4d8e-9e86-439875792b1a)
![image](https://github.com/PINTO0309/onnx2tf/assets/64444088/22b8b148-eb13-43e5-81c9-8bcc3bff8300)
I tried to understand and debug the problem, but I was not able to fix it. 
![image](https://github.com/PINTO0309/onnx2tf/assets/64444088/428935ac-52e1-4ca1-b70f-3ceb3cf0afc9)

Thank you for your help!

**Comment by PINTO0309** [comment]
No parameter substitution is required.
```
onnx2tf -i depth_anything_vits14_1x3x480x640.onnx -cotof -cotoa 1e-3
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/233f223a-b910-4044-88de-d0efd11dc7db)
