### ISSUE TITLE
how to fuse activation into conv: fused_activation_function=NONE

### ISSUE THREAD

**Issue by helloworld77** [PINTO0309/onnx2tf#613]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.10.0

### onnx version number

1.10.2

### onnxruntime version number

none

### onnxsim (onnx_simplifier) version number

none

### tensorflow version number

2.13.0

### Download URL for ONNX

https://github.com/onnx/models/blob/main/Computer_Vision/resnet18_Opset18_torch_hub/resnet18_Opset18.onnx

### Parameter Replacement JSON

```json
none
```

### Description

1. Run fast on NPU by tflite nnapi support
2. Tensorflow official quant model: http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz, in this model, relu6 activation is fuse into conv and fused_activation_function=NONE
3. I tried to analysis this quant mode, and I found that was compatible with tensorflow <= 1.12.x.
4. Fuse activation into conv ops could make the run fast in unisoc.
5. I tried to convert [resnet18_Opset18.onnx](https://github.com/onnx/models/blob/main/Computer_Vision/resnet18_Opset18_torch_hub/resnet18_Opset18.onnx ) by onnx-tf, but I can't get fused_activation_function=NONE.

**Comment by PINTO0309** [comment]
> relu6 activation is fuse into conv

It is completely wrong.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/b395f1d9-2e53-497d-adbb-eb7f17395b95)

No wonder.

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/8ea613ca-e629-4808-965b-cc84ed49ccb3)

**Comment by helloworld77** [comment]
> > relu6 activation is fuse into conv
> 
> It is completely wrong.
> 
> ![image](https://private-user-images.githubusercontent.com/33194443/325799998-b395f1d9-2e53-497d-adbb-eb7f17395b95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTQ1NjgsIm5iZiI6MTcxNDA5NDI2OCwicGF0aCI6Ii8zMzE5NDQ0My8zMjU3OTk5OTgtYjM5NWYxZDktMmU1My00OTdkLWFkYmItZWI3ZjE3Mzk1Yjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZjI0NTc2YjE2ZTE4NWE2MGIzNGI5NDk2YWM3MTc4NjA2NDNjOWVjOGRlNWQ5YWY4MzliMDFkM2UxYWIwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gZ-Den4IgYeqpjzgHmcGChoANWBArYVRThP8POHdIuw)
> 
> No wonder.
> 
> ![image](https://private-user-images.githubusercontent.com/33194443/325800107-8ea613ca-e629-4808-965b-cc84ed49ccb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTQ1NjgsIm5iZiI6MTcxNDA5NDI2OCwicGF0aCI6Ii8zMzE5NDQ0My8zMjU4MDAxMDctOGVhNjEzY2EtZTYyOS00ODA4LTk2NWItY2M4NGVkNDljY2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAxMTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTJhNDM2YjRlYzEzN2ZjZjVlZGJmMmQ1ZWFmNzJiYTQ5ZDIzYmQ5MTVmOTVjMThlM2I0ZjgyNmE5MGQ2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PZ8L6RcK5UaPYcN4l8kjRLYUpoA-EXcvnl2Z2SN20ko)

Thanks for your Response~~
I don't think it was wrong. take a look at the scale and zero point formate:
<img width="836" alt="image" src="https://github.com/PINTO0309/onnx2tf/assets/16054417/9c84bfcd-30e5-4159-8b1a-74e00e431686">
The old formate compute the relu-like activation into the scale computation.

**Comment by PINTO0309** [comment]
I am posting only the reference URL for the research process as I have to be out of town for an extended period of time. I will check it when I get home.

https://stackoverflow.com/questions/62000090/how-does-tflite-fuses-relu-into-conv-layers

**Comment by helloworld77** [comment]
> I am posting only the reference URL for the research process as I have to be out of town for an extended period of time. I will check it when I get home.
> 
> https://stackoverflow.com/questions/62000090/how-does-tflite-fuses-relu-into-conv-layers

Thanks !
I found that this kind of fusion (fused_activation_function=NONE) was adopt by tensorflow<=1.12.x version, after this version, activation like relu was explicit fused_activation_function=RELU, there should be some switch button in latest tensorflow, because the type: [FusedActivationFunctionType::kNone](https://github.com/tensorflow/tensorflow/blob/114bce3e7254657f5cb1835717a3d366455f8692/tensorflow/lite/kernels/internal/types.h#L29) is still in main branch of tensorflow.
Thank you again for your great work.

**Comment by helloworld77** [comment]
> I am posting only the reference URL for the research process as I have to be out of town for an extended period of time. I will check it when I get home.
> 
> https://stackoverflow.com/questions/62000090/how-does-tflite-fuses-relu-into-conv-layers

I will take a look at this solution. Thanks again.

**Comment by PINTO0309** [comment]
I have looked at all of the API in v2.16.1 and there does not appear to be any flags or options that you would expect. Once I remove the TODO flag, the bot will automatically close this issue after 5 days if there is no new feedback from you.

**Comment by helloworld77** [comment]
> I have looked at all of the API in v2.16.1 and there does not appear to be any flags or options that you would expect. Once I remove the TODO flag, the bot will automatically close this issue after 5 days if there is no new feedback from you.

Thanks, It really seems not have that flags. I will use tf-v1.x as a solution.
