### ISSUE TITLE
Android GPU inference falls with TRANSPOSE_CONV: Max version supported: 3. Requested version 4.

### ISSUE THREAD

**Issue by gabrielpopa** [PINTO0309/onnx2tf#640]
### Issue Type

Feature Request

### OS

Others

### onnx2tf version number

1.22.0

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

private

### Parameter Replacement JSON

```json
no
```

### Description

Exporting a tflite using onnx2tf works fine, but falls back on the CPU when it meets a ConvTranspose layer with the error TRANSPOSE_CONV: Max version supported: 3. Requested version 4.

It runs fine on the CPU, but obviously slower.

It would be great if one could choose the version of the operation or I'm doing something wrong.

Should I change the ONNX file to use different ConvTranspose? 

Netron says:
module: ai.onnx v11
it has attributes of dilations, group, kernel_shape, pads, strides.

**Comment by PINTO0309** [comment]
It has nothing to do with the functionality of ONNX or onnx2tf. onnx2tf just calls the TensorFlow model converter in the middle of the process. 

I don't believe there is an API implemented in TensorFlow to specify the version of the operator. Therefore, please submit an issue in the TensorFlow repository.
