### ISSUE TITLE
Conversion error for Resize layer when using flag "-nuo"

### ISSUE THREAD

**Issue by amitk-OE** [PINTO0309/onnx2tf#641]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.17.5

### onnx version number

1.14.0

### onnxruntime version number

1.15.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.14.0-rc1

### Download URL for ONNX

[toy_with_constant_and_resize.onnx.zip](https://github.com/PINTO0309/onnx2tf/files/15446205/toy_with_constant_and_resize.onnx.zip)

### Parameter Replacement JSON

```json
{}
```

### Description

Thank you very much for your contribution!

Continuing issue #627, I failed to convert the attached toy model that includes a resize layer.

When I try to run "onnx2tf -i toy_with_constant_and_resize.onnx -osd -nuo" I get the following error -
TypeError: Could not build a TypeSpec for KerasTensor(type_spec=TensorSpec(shape=(1, None, None, 64), dtype=tf.float32, name=None), name='tf.compat.v1.image.resize_nearest_neighbor/ResizeNearestNeighbor:0', description="created by layer 'tf.compat.v1.image.resize_nearest_neighbor'") of unsupported type <class 'keras.src.engine.keras_tensor.KerasTensor'>.

The reason I want to use the flag -nuo is your comment in https://github.com/PINTO0309/onnx2tf/pull/628/files, for preserving constant outputs.

**Comment by PINTO0309** [comment]
Please examine the hundreds of commit logs yourself. I am not inclined to give advice on work that is outside of the main flow.
