### ISSUE TITLE
FusedConv error

### ISSUE THREAD

**Issue by tanphan07** [PINTO0309/onnx2tf#643]
### Issue Type

Others
### OS

Linux

### onnx2tf version number

1.22.3

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

[lm_model4_opt.onnx.zip](https://github.com/user-attachments/files/15510495/lm_model4_opt.onnx.zip)

### Parameter Replacement JSON

```json
-
```

### Description

![Screenshot from 2024-05-31 14-14-09](https://github.com/PINTO0309/onnx2tf/assets/91008694/5def81ae-e8e0-43fb-879c-c66a75ae73a4)
I can not convert this onnx model to tflite. When i convert, i have this error. Can you support me to handle this problem

**Comment by PINTO0309** [comment]
Fix: https://github.com/PINTO0309/onnx2tf/releases/tag/1.22.4

**Comment by tanphan07** [comment]
> Fix: https://github.com/PINTO0309/onnx2tf/releases/tag/1.22.4

thank you for your quick reply. Can you give me a fp16 version.

**Comment by PINTO0309** [comment]
Do it yourself.
