### ISSUE TITLE
matmul uint8 converts to flexbatchmatmul

### ISSUE THREAD

**Issue by tensorbuffer** [PINTO0309/onnx2tf#648]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.22.4

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

[matmul.zip](https://github.com/user-attachments/files/15604383/matmul.zip)

### Parameter Replacement JSON

```json
No need, since I used your docker image.
```

### Description

1. Purpose: trying to get a tflite model with a single fullyconnected layer that's converted from onnx matmul.
2. What: I tried with docker image (docker.io/pinto0309/onnx2tf:1.22.4), and added parameter  -rtpo MatMulInteger, but still got a tflite model with flexbatchmatmul.
3. How: this is how I run the command within docker:
user@b47d54f3bb8e:/workdir$ sudo onnx2tf -i matmul_model.uint8.onnx -o output.uint8 -rtpo MatMulInteger
(the model is uploaded as zip file)
4. Why: because I need such a model to feed to our hw accelator
5. Resource: none

**Comment by PINTO0309** [comment]
onnx2tf (TensorFlow Lite) can only generate Float32 MatMul, is that ok?

**Comment by tensorbuffer** [comment]
Thanks for the quick response!
My end goal is to have a matmul with uint8 (or int8) to test our hw accelerator.
I first tried with int8 and I got this error when I do onnx2tf:
Value passed to parameter 'x' has DataType int8 not in list of allowed values: bfloat16, float16, float32, float64, int16, int32, int64, uint8, uint16, uint32, uint64, complex64, complex128
So I thought uint8 is a valid data type.
I can use float and generate the fullyconnected layer fine, but our hw doesn't support float yet. I probably can try float with quantization? then the result won't match exactly since floats have different representation between hw and host...

**Comment by PINTO0309** [comment]
Use Float32 onnx. And you can quantize to uint8 with just two options `-oiqt`, `-qt uint8`. 

onnx2tf was initially designed with a strong emphasis on optimizing for hardware accelerators dedicated to quantization models, such as EdgeTPU and Hailo-8.

Instead of trying to quantize int8 or uint8 on the onnx side, it should be quantized directly in onnx2tf or TensorFlow.

You have complicated the story.
