### ISSUE TITLE
Input and Output Name Order Swapping with -coion option

### ISSUE THREAD

**Issue by ysohma** [PINTO0309/onnx2tf#650]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.22.4

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

N/A. 
provide by an attachment.

### Parameter Replacement JSON

```json
N/A.
```

### Description

1. Purpose: Research
2. What & 3. How & 4. Why

When using the -coion option, the order of input and output names may sometimes swap.

### Reproduction Steps
Prepare a simple model with two inputs (input0, input1) with different shapes for identification.
<img width="366" alt="viz_onnx_model" src="https://github.com/PINTO0309/onnx2tf/assets/74748700/85bd8601-9010-4c3c-a1bd-cfe627e1c47c">

Convert the model using the following command:

```bash
onnx2tf -i sample.onnx -o outputs -coion -oiqt
```
Observe the converted models for both the floating-point model (float32) and the fully integer-quantized model (full_integer_quant)

#### outputs/sample_float32.tflite
<img width="305" alt="viz_full_integer_quant_model" src="https://github.com/PINTO0309/onnx2tf/assets/74748700/ff565a4a-06ba-4f9f-b355-2158fbe6e6cd">

#### outputs/sample_full_integer_quant.tflite
<img width="278" alt="viz_float32_model" src="https://github.com/PINTO0309/onnx2tf/assets/74748700/413431c4-aa89-4e12-8c1b-8ec3c3253a97">

In the floating-point model, input0 and input1 are correctly reflected, but in the fully integer-quantized model, input0 and input1 are swapped.

This indicates that when using the -coion option with models that have multiple inputs and outputs, the fully integer-quantized model may have discrepancies in input and output names compared to the original ONNX model.

### Analysis
To identify the cause of this issue, debug code was inserted into the onnx2tf source around [here](https://github.com/PINTO0309/onnx2tf/blob/main/onnx2tf/utils/common_functions.py#L4614-L4619)
<img width="772" alt="image" src="https://github.com/PINTO0309/onnx2tf/assets/74748700/0c386749-83f8-4d29-9724-e228acc391dd">

It was found that the order of inputs/outputs in the flatbuffer does not match the order in the original ONNX model.
<img width="745" alt="debug_log" src="https://github.com/PINTO0309/onnx2tf/assets/74748700/d94bdf4f-5e9d-447b-b830-24ecee4fa46b">

In the conversion of the floating-point model, the TFLiteConverter is created directly from the concrete_function. However, for the fully integer-quantized model, the TFLiteConverter is created from a SavedModel with signaturedefs. This difference in method causes the order mismatch.

5. Resources
[resources.zip](https://github.com/user-attachments/files/15981269/resources.zip)

**Comment by PINTO0309** [comment]
I was aware of that possible problem when I implemented this feature. Whether you use `concrete_function` or not, the result is the same.

- conc
  ```python
              # INT8 Converter
              # converter = tf.lite.TFLiteConverter.from_saved_model(
              #     output_folder_path,
              # )
              converter = tf.lite.TFLiteConverter.from_concrete_functions(
                  [concrete_func]
              )
  ```
- run
  ```
  onnx2tf -i sample.onnx -o outputs -coion -oiqt
  ```
- result
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/33b7dade-21a6-44eb-8527-4eddd036a3dd)

Frankly, I can't think of a way to make the name order consistent with ONNX since the beginning of the creation of `-coion`.

**Comment by PINTO0309** [comment]
- test
  ![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/50a4e3c3-fd92-401b-938c-b4833e15e916)

**Comment by ysohma** [comment]
I understand that this issue is related to TensorFlow itself rather than onnx2tf. 
For my purposes, modifying the output INT8 model can be acceptable.

Thanks!

**Comment by PINTO0309** [comment]
I will release v1.22.5 in a few more ten minutes.
