### ISSUE TITLE
Error when without -dgc:  onnx2tf.py -i shufflenet-9.onnx -oiqt

### ISSUE THREAD

**Issue by hayyaw** [PINTO0309/onnx2tf#657]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.23.0

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

https://github.com/onnx/models/blob/main/validated/vision/classification/shufflenet/model/shufflenet-9.onnx

### Parameter Replacement JSON

```json
no
```

### Description

Error when without -dgc:  onnx2tf.py -i shufflenet-9.onnx -oiqt

**Comment by PINTO0309** [comment]
```
onnx2tf -i shufflenet-9.onnx -oiqt
```
![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/b2309174-a34c-496f-8be8-d833c608e0a9)

**Comment by hayyaw** [comment]
I can not pull onnx2tf:1.23.0 docker. I can obtain the lastest docker version is 1.22.4.  So, I use 1.23.0 code with 1.22.4 docker:sudo python onnx2tf/onnx2tf.py -i benchmark/shufflenet-9.onnx -oiqt -cotof. However, groupconv converter result is group nums' conv.  The model size is 49M 
![image](https://github.com/PINTO0309/onnx2tf/assets/119873470/75579292-5582-4fd4-a7a0-45556e67e298)
How should I get the same result as the picture above?

**Comment by PINTO0309** [comment]
I redeployed with v1.23.2 because the GitHub Actions spec had changed and deploying Docker images via CI was failing.
```
docker run --rm -it \
-v `pwd`:/workdir \
-w /workdir \
docker.io/pinto0309/onnx2tf:1.23.2
```
