### ISSUE TITLE
unmatched shape of GlobalAveragePool

### ISSUE THREAD

**Issue by PriceWang** [PINTO0309/onnx2tf#658]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.22.4

### onnx version number

1.16.1

### onnxruntime version number

1.18.0

### onnxsim (onnx_simplifier) version number

0.4.36

### tensorflow version number

2.16.1

### Download URL for ONNX

https://huggingface.co/PriceWang/maecg_micro/resolve/main/vit_atto_patch32.onnx

### Parameter Replacement JSON

```json
N/A
```

### Description

1. Purpose: Research development
2. What:

    I tried to convert .onnx to .tflite with 
`convert(input_onnx_file_path="./ckpts/test.onnx",
    output_folder_path="./ckpts/",
    batch_size=1,
    output_signaturedefs=True,
    not_use_onnxsim=True)`

    and got error

    
    <img width="1421" alt="1" src="https://github.com/PINTO0309/onnx2tf/assets/30796250/ef6a63e3-22a7-407f-8dec-860d65996d36">

    It seems the error occurs in GlobalAveragePool that uses the wrong dim.

    
    <img width="1421" alt="2" src="https://github.com/PINTO0309/onnx2tf/assets/30796250/bc4c9235-7e3a-4093-aee3-e87982d42b43">

3. How: No idea for this issue now
4. Why: I want to generate a tfite model from onnx

**Comment by PINTO0309** [comment]
```
onnx2tf -i vit_atto_patch32.onnx -kat input
```

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/5eeadf48-57fc-4bfd-b871-1b8bc1f00aa3)

![image](https://github.com/PINTO0309/onnx2tf/assets/33194443/83d3e00a-3c97-4907-8353-aaea89852f06)
