### ISSUE TITLE
InceptionV3 model convert result not as expected.

### ISSUE THREAD

**Issue by hayyaw** [PINTO0309/onnx2tf#662]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.23.2

### onnx version number

1.15.0

### onnxruntime version number

1.17.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.16.1

### Download URL for ONNX

![image](https://github.com/PINTO0309/onnx2tf/assets/119873470/0bd5cb8d-0fd5-472c-bea9-4691dbc45789)

### Parameter Replacement JSON

```json
no
```

### Description

onnx model
![image](https://github.com/PINTO0309/onnx2tf/assets/119873470/e064ea24-d75e-46a5-a926-3268bf2f078b)

Full INT8 Quantization tflite
![image](https://github.com/PINTO0309/onnx2tf/assets/119873470/c01e1cc9-d3e4-4a6a-8249-93689cec928f).     

command:
onnx2tf.py -i inception_v3_Opset18.onnx -oiqt

the part structure of full INT8 Quantization tflite is so different from the origin onnx model. Is it a bug? Can it be simplified as the structure of onnx model with quantized tflite op? Thanks!

**Comment by PINTO0309** [comment]
>Is it a bug? 

No.

https://github.com/PINTO0309/onnx2tf/pull/138
https://github.com/PINTO0309/onnx2tf/pull/151
https://github.com/PINTO0309/onnx2tf/pull/211
