### ISSUE TITLE
[YOLOvN] failed tf to tflite convertion

### ISSUE THREAD

**Issue by R4Ajeti** [PINTO0309/onnx2tf#676]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.25.7

### onnx version number

1.16.2

### onnxruntime version number

1.18.1

### onnxsim (onnx_simplifier) version number

1.0.4

### tensorflow version number

2.17.0

### Download URL for ONNX

pip install onnx2tf
Yolov9 custom model onnx

### Parameter Replacement JSON

```json
{}
```

### Description

error

ERROR: input_onnx_file_path: best-striped-model-final.onnx
ERROR: onnx_op_name: wa/model.3/AveragePool
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.

**Comment by koush** [comment]
Here is a model with a repro:
https://github.com/koush/onnx-models/blob/main/scrypted_yolov9t_320/best.onnx

onnx2f -i best.onnx

**Comment by PINTO0309** [comment]
```python
import onnx
from pprint import pprint

model = onnx.load('best.onnx')
metadata_props = model.metadata_props

pprint(metadata_props)
```
```
[key: "stride"
value: "32"
, key: "names"
value: "{0: \'person\', 1: \'vehicle\', 2: \'animal\'}"
, key: "names"
value: "{0: \'person\', 1: \'vehicle\', 2: \'animal\'}"
]
```

**Comment by koush** [comment]
thanks, that was the issue
