### ISSUE TITLE
int8 version of mobilenetv3 has bad accuracy

### ISSUE THREAD

**Issue by ogvalt** [PINTO0309/onnx2tf#683]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.25.7

### onnx version number

1.16.1

### onnxruntime version number

1.18.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.17.0

### Download URL for ONNX

https://drive.google.com/file/d/1jwBQWJG_zUcO4STFiPCxFnDMgkZJnA80/view?usp=sharing

### Parameter Replacement JSON

```json
{}
```

### Description

1. This is a part of product development. We are putting this model on Coral TPU as part of our hardware roadmap.
2. It isn't an error per say, it just that the model not even close to the outputs that float32 model version gives. This leads to results of futher pipeline being useless. 
3. Well I've tried to change `-qt` from `per-channel` to `per-tensor`; provide custom calibrated data. 
4. Part of product development.
5. My latest command to run convertion:
```
onnx2tf -i backbone-127/backbone-127-127.onnx -oiqt \
    -qt per-tensor -coton "denorm" \
    -b 1 \
    -cind "input" "calib_127.npy" "[0]" "[1]"
```

This model is a strip off MobileNetV3 without couple of final layers. 
My next step would be to make layer by layer check, but I would like to avoid it, because it's very tedious. 
So maybe you know some hack that I did not consider, that make model behave.

**Comment by PINTO0309** [comment]
```bash
onnx2tf -i backbone-127-127.onnx -cotof
```
![image](https://github.com/user-attachments/assets/4cc4fa8b-4e43-41aa-b939-a9f4e716078b)

https://github.com/PINTO0309/onnx2tf?tab=readme-ov-file#7-if-the-accuracy-of-the-int8-quantized-model-degrades-significantly
