### ISSUE TITLE
Wrong shape converted for GIST-all-MiniLM-L6-v2

### ISSUE THREAD

**Issue by superjackie** [PINTO0309/onnx2tf#687]
### Issue Type

Others

### OS

Windows

### onnx2tf version number

1.25.9

### onnx version number

1.16.2

### onnxruntime version number

 1.19.2

### onnxsim (onnx_simplifier) version number

0.4.36

### tensorflow version number

2.17.0

### Download URL for ONNX

https://huggingface.co/avsolatorio/GIST-all-MiniLM-L6-v2/resolve/main/onnx/model.onnx?download=true

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose: convert GIST-all-MiniLM-L6-v2 onnx model to tflite
2. command run on x86 windows11 WSL: onnx2tf -i model.onnx -osd -coion -b 1
3. Issue: incorrect shape for this node:
![image](https://github.com/user-attachments/assets/8e8bec3d-a340-4f40-904f-dd35d2fd8f39)
![image](https://github.com/user-attachments/assets/1d7b093f-98f5-4371-ac94-2262a2020c4f)
4. log:
[log.txt](https://github.com/user-attachments/files/16906254/log.txt)

**Comment by PINTO0309** [comment]
TODO: https://github.com/PINTO0309/onnx2tf/commit/28d98afbad3d00cd018ef6caea65ae42c5ccfb4e

**Comment by PINTO0309** [comment]
The architecture of this tool is not able to meet your request. Please try the following tools:

1. https://github.com/google-ai-edge/ai-edge-torch
2. https://github.com/AlexanderLutsenko/nobuco

https://github.com/PINTO0309/onnx2tf/commit/4268bcfbf6ad467c5156c04ed7e8a68139cb1d0e

**Comment by superjackie** [comment]
> [4268bcf](https://github.com/PINTO0309/onnx2tf/commit/4268bcfbf6ad467c5156c04ed7e8a68139cb1d0e)
> 
> The architecture of onnx2tf is not able to meet your request. Please try the following tools:
> 
> 1. https://github.com/google-ai-edge/ai-edge-torch
> 2. https://github.com/AlexanderLutsenko/nobuco

Thanks, I'll try that.
