### ISSUE TITLE
Update to improve mAP ?

### ISSUE THREAD

**Issue by PetiteFleurPF** [PINTO0309/onnx2tf#691]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.25.7

### onnx version number

1.16.0

### onnxruntime version number

1.17.3

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.17.0

### Download URL for ONNX

Every mobilenet (I tested them all in terms of type)

### Parameter Replacement JSON

```json
.
```

### Description

I have a huge mAP drop with my quantized models - and would like to know if you have any tips on how to avoid this :) I appreciate any help you can give me. 

NB: in the description of your package on PyPi, you wrote:  Does not support quantization to INT8. For quantization, use the official TensorFlow converter to convert from saved_model to your own.

**Comment by PINTO0309** [comment]
> in the description of your package on PyPi, you wrote: Does not support quantization to INT8. 

I haven't written that anywhere.

https://github.com/PINTO0309/onnx2tf?tab=readme-ov-file#7-if-the-accuracy-of-the-int8-quantized-model-degrades-significantly

https://github.com/PINTO0309/onnx2tf?tab=readme-ov-file#7-if-the-accuracy-of-the-int8-quantized-model-degrades-significantly

https://github.com/PINTO0309/onnx2tf?tab=readme-ov-file#12-if-the-accuracy-of-the-float32-model-degrades-significantly

**Comment by PetiteFleurPF** [comment]
Ok so no update and the sentence is from "https://pypi.org/project/onnx2tf/1.0.6/" which is the second link when you search "onnx2tf" on google. Which is, I am agree, not you latest version when you check the version number. 

![image](https://github.com/user-attachments/assets/dca5f825-3c7c-45b3-89ba-856471388491)

Sorry for the inconvenience, have a nice day.
