### ISSUE TITLE
Confusion about "Quantization error simulation of SiLU(Swish) Activation"

### ISSUE THREAD

**Issue by Reciphon** [PINTO0309/onnx2tf#693]
### Issue Type

Others

### OS

Windows

### onnx2tf version number

None

### onnx version number

None

### onnxruntime version number

None

### onnxsim (onnx_simplifier) version number

None

### tensorflow version number

None

### Download URL for ONNX

None

### Parameter Replacement JSON

```json
None
```

### Description

Question:
Why is the input to ReLU not fake_quantized? Is there something specific regarding hardware implementation?

In Motokimura's implementation, whether "quantize" is set to true or false, the input 𝑥 for ReLU won't go through a "fake_quantize". As a result, the SQNR values are as follows.
ReLU SQNR[dB]: 41.78247482162445
SiLU SQNR[dB]: 31.143257418315898

Motokimura's Function Definition of ReLU:
```python
def relu(x, quantize=False):
    quantize_fn = fake_quantize if quantize else (lambda x: x)
    return quantize_fn(x.clip(min=0))
```

However, when "fake_quantize" is also applied to the input 𝑥 for ReLU , the SQNR are as follows, with the difference between ReLU and SiLU being narrower.
ReLU SQNR[dB]: 33.57212187862955
SiLU SQNR[dB]: 31.390906241815845

Modified Function Definition of ReLU:
```python
def relu(x, quantize=False):
    quantize_fn = fake_quantize if quantize else (lambda x: x)
    return quantize_fn(quantize_fn(x).clip(min=0))
```

Except the mentioned modification to the definition of the ReLU function, everything else remains unchanged.

**Comment by PINTO0309** [comment]
@motokimura Thank you very much for verifying the accuracy of quantization so far. As mentioned above, I have some questions about the verification code, so I would appreciate your feedback.

**Comment by motokimura** [comment]
@Reciphon Thank you for pointing this out. You’re right. To fairly compare SiLU and ReLU, the input to ReLU should also have been quantized. I've updated the Gist.

https://gist.github.com/motokimura/1a90c0b8c5628914b99a81cd91369636

```python
def relu(x, quantize=False):
    quantize_fn = fake_quantize if quantize else (lambda x: x)
    h = quantize_fn(x)  # quantize input
    h = h.clip(min=0)  # relu operation
    return quantize_fn(h)  # quantize output
```

**Comment by PINTO0309** [comment]
Docs updated: https://github.com/PINTO0309/onnx2tf/tree/main?tab=readme-ov-file#7-if-the-accuracy-of-the-int8-quantized-model-degrades-significantly

**Comment by Reciphon** [comment]
Thanks for the quick reply and confirmation ; ).
