### ISSUE TITLE
Dealing with quantized onnx - ie int8; mixed int8/fp32; etc

### ISSUE THREAD

**Issue by Alexey234432** [PINTO0309/onnx2tf#697]
### Issue Type
Documentation Feature Request

### Description
Hi, Thank you for the great work.

I am curious whether onnx2tf can be used to transfer more advanced quantizations / quantizations which are already present in onnx to tflite (ie can we use int8 onnx model as a starting point)? or the only supported path is to start with fp32 onnx model and then perform all quantization with Tensorflow?

Thank you

**Comment by PINTO0309** [comment]
> can we use int8 onnx model as a starting point?

No. We can't. Dup: https://github.com/PINTO0309/onnx2tf/issues/680
However, to be precise, this can be achieved by adding extensive logic to generate the FlatBuffer manually. However, I have no idea what the benefits would be for me to bear such a huge amount of work costs, so I have no plans to implement it.


Ref: https://github.com/PINTO0309/onnx2tf/issues?q=label%3AQuantization
