### ISSUE TITLE
Add transposition to the tflite model

### ISSUE THREAD

**Issue by pipipyau** [PINTO0309/onnx2tf#700]
### Issue Type

Feature Request

### OS

OSX

### onnx2tf version number

1.25.12

### onnx version number

1.16.2

### onnxruntime version number

1.19.2

### onnxsim (onnx_simplifier) version number

0.4.36

### tensorflow version number

2.17.0

### Download URL for ONNX

https://drive.google.com/file/d/18IkWTktKG2wTvtjnrjsNodD9ri4jmLZE/view?usp=drive_link

### Parameter Replacement JSON

```json
{}
```

### Description

1. I am studying model conversion as part of my Research  development at the university.
2. Need to leave the option to use the same input data as for the onnx model for tflite model. simple example is (1,3,224,224) (NCHW), but my obtained (from onnx) tflite model have NHWC input and no transpose layer.
3. I tried to use flags when converting `-k`
4. This task takes into account that when replacing the model, it will not be possible to change the input data

**Comment by PINTO0309** [comment]
I'm sorry, but I don't understand what you're expecting.
```
onnx2tf -i conv_model.onnx
```
![image](https://github.com/user-attachments/assets/dbc45d33-39e7-46b7-b8f5-448b76dfc40d)
```
onnx2tf -i conv_model.onnx -kat input
```
![image](https://github.com/user-attachments/assets/7138cb1b-eb90-4dbf-9693-652c264395b7)

**Comment by pipipyau** [comment]
Thank you for your reply! I used the `-k` flag incorrectly. And what about the output - is it possible to keep the shape there by adding a transposition (1, 16, 224, 224)?

**Comment by PINTO0309** [comment]
WIP: https://github.com/PINTO0309/onnx2tf/tree/rep_param_conv

- replace_conv.json
  ```json
  {
    "format_version": 1,
    "operations": [
      {
        "op_name": "wa/conv/Conv",
        "param_target": "outputs",
        "param_name": "output",
        "post_process_transpose_perm": [0,3,1,2]
      }
    ]
  }
  ```
- test
  ```
  onnx2tf -i model_conv.onnx -kat input -prf replace_conb.json
  ```
  ![image](https://github.com/user-attachments/assets/9f1668da-c73d-4f90-a1fa-069b93e0a33b)

**Comment by pipipyau** [comment]
Thanks for your work✨

**Comment by PINTO0309** [comment]
Fix: https://github.com/PINTO0309/onnx2tf/releases/tag/1.26.0
