### ISSUE TITLE
README corrections due to API changes (I'll get serious from tomorrow)

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/onnx2tf#702]
### Issue Type

Documentation Feature Request, Others

### OS

Linux

### onnx2tf version number

1.25.15

### onnx version number

1.16.1

### onnxruntime version number

1.18.1

### onnxsim (onnx_simplifier) version number

0.4.33

### tensorflow version number

2.17.0

### Download URL for ONNX

NA

### Parameter Replacement JSON

```json
NA
```

### Description

- Update README
  https://github.com/PINTO0309/onnx2tf/pull/701

**Comment by marcoschepis** [comment]
If you want, I updated also the readme

**Comment by PINTO0309** [comment]
@marcoschepis Wow. Thank you!
