### ISSUE TITLE
Unable to convert Phi-3.5-mini-instruct-onnx to tflite format

### ISSUE THREAD

**Issue by beefho67** [PINTO0309/onnx2tf#720]
### Issue Type

Others

### OS

Linux

### onnx2tf version number

1.26.2

### onnx version number

1.17.0

### onnxruntime version number

1.19.2

### onnxsim (onnx_simplifier) version number

0.4.36

### tensorflow version number

2.18.0

### Download URL for ONNX

https://pypi.org/project/onnx/

### Parameter Replacement JSON

```json
{}
```

### Description

1. Purpose:  Research. It will help us convert the onnx to tflite and make it possible to run different models on Android device.
2. What: I'd like to convert the model [Phi-3.5-mini-instruct-onnx](https://huggingface.co/microsoft/Phi-3.5-mini-instruct-onnx/tree/main/cpu_and_mobile/cpu-int4-awq-block-128-acc-level-4) to tflite one with onnx2tf. However, I got the following error.
![image](https://github.com/user-attachments/assets/1cc3dd55-5668-4be8-b2cd-696c113cdc96)

3. How: I tried to solve the problem by reading [this ](https://pypi.org/project/onnx2tf) but haven't got any luck.
4. Why: It's declared that we can convert PyTorch models into tflite ones by ai-edge-torch. However, the converted one does not perform well. That's why we are seeking alternative solutions.
5. Resource: https://pypi.org/project/onnx2tf

**Comment by PINTO0309** [comment]
dup: https://github.com/PINTO0309/onnx2tf/issues/647
