### ISSUE TITLE
When my model is conv3d, avgpool3d seems to have some issues

### ISSUE THREAD

**Issue by jungyin** [PINTO0309/onnx2tf#722]
### Issue Type

Feature Request

### OS

Linux

### onnx2tf version number

1.26.2

### onnx version number

1.16.1

### onnxruntime version number

1.18.1

### onnxsim (onnx_simplifier) version number

0.4.36

### tensorflow version number

2.17.0

### Download URL for ONNX
https://1drv.ms/u/c/4008ad016f04b6a0/ET1fYPRg0fxNk9NAPr870pkBcKNHr_xKjm7wZF5Ii2hXLg?e=nKf0KE

### Parameter Replacement JSON

```json
{
    "inputs": [
        {
            "name": "input_0",
            "shape": [
                1,
                3,
                150,
                128,
                128
            ]
        }
    ],
    "outputs": [
        {
            "name": "face_PPG",
            "shape": [
                1,
                150
            ]
        },
        {
            "name": "finger_PPG",
            "shape": [
                1,
                150
            ]
        }
    ]
}
```

### Description

My model structure is conv3d, and its input type is ncdhw. When I try to convert the onnx model to tflite, there is always an error in the screenshot. After changing it to a fixed value, it can export the model normally. I am not sure if this modification is correct. Can you provide me with some guidance

![image](https://github.com/user-attachments/assets/70dab64c-06db-49ca-9de6-2368bce0bed6)

**Comment by PINTO0309** [comment]
onnx

**Comment by jungyin** [comment]
> onnx 文件

i was update https://1drv.ms/u/c/4008ad016f04b6a0/ET1fYPRg0fxNk9NAPr870pkBcKNHr_xKjm7wZF5Ii2hXLg?e=nKf0KE

**Comment by PINTO0309** [comment]
TensorFlow cannot pool properly when `count_include_pad = 1`. https://github.com/PINTO0309/onnx2tf/issues/124

**Comment by jungyin** [comment]
> TensorFlow cannot pool properly when `count_include_pad = 1`. see: #124
> 
> https://github.com/onnx/onnx/blob/main/docs/Changelog.md#averagepool-11
> 
> * AveragePool-11
>   ![image](https://private-user-images.githubusercontent.com/33194443/385297708-c3003dce-b3bf-4988-b9d8-822af286a49c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTUzNzMsIm5iZiI6MTczMTU1NTA3MywicGF0aCI6Ii8zMzE5NDQ0My8zODUyOTc3MDgtYzMwMDNkY2UtYjNiZi00OTg4LWI5ZDgtODIyYWYyODZhNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNmUxZjE3NDU1ZGY5N2NmMWVhMDdmYjYyMDQxYjkxN2Y5NWIxZGNlYWI4OTE1YjVkYmM5OTczYTMyNjFjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vOnk5v-gtK1lEp9rHXvnkSbQUr-Dsi6gaZ04AYFK65U)
> 
> ![image](https://private-user-images.githubusercontent.com/33194443/385299593-38fab7da-1051-4e11-bddd-5b723ffba688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTUzNzMsIm5iZiI6MTczMTU1NTA3MywicGF0aCI6Ii8zMzE5NDQ0My8zODUyOTk1OTMtMzhmYWI3ZGEtMTA1MS00ZTExLWJkZGQtNWI3MjNmZmJhNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzMzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDI3NDM4YWQyMWU0NGRmZWExNWFiMzY3NmZjYjA1NThmNmM4ODQyMzM1NGRiN2I4NWMyMDM3NDQzNDZjNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jYZav8U9LxcMYqXxYy_fkJWkFedgV1v6fF-plhALt8I)

It seems that this approach requires adjustments to the existing model, and such adjustments may require me to retrain the model? Besides, you can take a look. After I made changes to the source code, this error will pause the report. Is this modification correct? Looking forward to your reply, thank you very much!

**Comment by PINTO0309** [comment]
Check the accuracy of the model by specifying the `-cotof` option. It is probably incredibly inaccurate.

>It seems that this approach requires adjustments to the existing model, and such adjustments may require me to retrain the model?

Unfortunately, that's right.

**Comment by jungyin** [comment]
> Check the accuracy of the model by specifying the option. It is probably incredibly inaccurate.`-cotof`
> 
> > It seems that this approach requires adjustments to the existing model, and such adjustments may require me to retrain the model?
> 
> Unfortunately, that's right.

i was try add -cotof,it print this，maby it is surcess work?
![image](https://github.com/user-attachments/assets/c9c436c9-7d8a-40d7-8a99-a96d62d3144d)
