### ISSUE TITLE
Not able to reshape input in replace.json

### ISSUE THREAD

**Issue by longngng** [PINTO0309/onnx2tf#8]
### Issue Type

Others

### onnx2tf version number

1.0.27

### Download URL for ONNX

https://drive.google.com/file/d/1Wkb-xi8NBICJttIyctUL3m7ETGHv2BZ8/view

### Parameter Replacement JSON

```json
{
    "format_version": 1,
    "operations": [
        {
            "op_name": "Flatten_10",
            "param_target": "inputs",
            "param_name": "input.16",
            "pre_process_transpose_perm": [3,1,2,0]
        },
        {
            "op_name": "Flatten_10",
            "param_target": "outputs",
            "param_name": "onnx::Gemm_31",
            "post_process_transpose_perm": [1, 0]
        }
    ]
}
```

### Description

1. School research project on TinyML.
2. I have simplified the model with onnxsim, then I ran this command `onnx2tf -i baseline_simplified.onnx -b 1` 

The onnx model has a Flatten layer. Input shape is ['batch_size', 32, 1, 3], output shape is ['batch_size', 96]. The OP get converted to tf.reshape, the input shape is (1, 1, 3, 32), output shape is (3, 32). 
![image](https://user-images.githubusercontent.com/46754292/198350055-84189014-8620-42e6-a493-670efa558e81.png)

3. I attempted to solve it with the Parameter Replacement JSON to tranpose both the input and output. The transpose for the output works, but the transpose for the input gives me this error. 
![image](https://user-images.githubusercontent.com/46754292/198350209-e5c503f3-ea16-43e4-9a92-92390d6a8a81.png)

4. I need the tflite model so that I can quantise it and deploy using TFLiteMicro.
5. I have tried to use openvino library to convert onnx to openvino, then openvino to tf. I can convert but the output of tf model is very different from the onnx output.

**Comment by PINTO0309** [comment]
1. there was a bug in the parameter transposition logic that I have fixed. Thanks for pointing this out. Fixes: fca5c2a589c2d05c6c8003c1faa7cf124dbba418
2. `Parameter Replacement JSON` can be written as follows to correctly modify `Flatten` behavior. Please try it.
```json
{
  "format_version": 1,
  "operations": [
    {
      "op_name": "Flatten_10",
      "param_target": "inputs",
      "param_name": "input.16",
      "pre_process_transpose_perm": [0,3,1,2]
    },
    {
      "op_name": "Flatten_10",
      "param_target": "attributes",
      "param_name": "axis",
      "values": 1
    }
  ]
}
```

The optimization will be suboptimal with variable batch sizes. We recommend changing the batch size to a fixed size whenever possible. If the batch size is variable (`batchsize`), the shape estimation process before and after Flatten (Reshape) becomes redundant. When using TFLiteMicro, I assume that you are aiming to optimize performance to the limit, so it would be better to avoid redundant models such as the one shown below to further improve performance.
- Before ONNX
![image](https://user-images.githubusercontent.com/33194443/198418786-e8d99ca7-1d0b-4b33-9ae9-94727507fab9.png)
- After TFLite
![image](https://user-images.githubusercontent.com/33194443/198418902-9e7e4653-aec0-47dc-8f3f-43491eb40e83.png)


model: [model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/9883729/model_float32.tflite.zip)
![image](https://user-images.githubusercontent.com/33194443/198418385-7e1cdc2c-7fae-47db-bd92-1a8237e03d09.png)

**Comment by longngng** [comment]
The conversion works now. Thank you very much for the fix and detailed explanation!

**Comment by PINTO0309** [comment]
Partial fix, Ref: https://github.com/PINTO0309/onnx2tf/commit/8954da065c3674e137a5d5961f448a4fc86523f6
Improved replace.json to be unnecessary only in some situations.
